<a href="https://colab.research.google.com/github/hjiwoong/bigdata/blob/main/api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4d82566d

In [2]:
import requests #HTTP 요청을 보내기 위한 requests 라이브러리
import pandas as pd
import pprint

In [4]:
url = "https://www.omdbapi.com/"
params = { #API 요청에 필요한 파라미터들을 딕셔너리로 정의
    "apikey":"4d82566d",
    "t":"Avengers",
    "type":"movie",
    "y":"2012"
}
#GET 요청
response = requests.get(url,params=params)
print(response.status_code) #HTTP 응답 상태 코드(예: 200은 성공)를 출력

200

In [7]:
#JSON 응답을 파이썬 객체로 변환
data = response.json() #응답 본분을 JSON 형식으로 파싱하여 파이썬 딕셔너리로 변환
pprint.pprint(data)

{'Actors': 'Robert Downey Jr., Chris Evans, Scarlett Johansson',
 'Awards': 'Nominated for 1 Oscar. 40 wins & 81 nominations total',
 'BoxOffice': '$623,357,910',
 'Country': 'United States',
 'DVD': 'N/A',
 'Director': 'Joss Whedon',
 'Genre': 'Action, Sci-Fi',
 'Language': 'English, Russian',
 'Metascore': '69',
 'Plot': "Earth's mightiest heroes must come together and learn to fight as a "
         'team if they are going to stop the mischievous Loki and his alien '
         'army from enslaving humanity.',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg',
 'Production': 'N/A',
 'Rated': 'PG-13',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'},
             {'Source': 'Rotten Tomatoes', 'Value': '91%'},
             {'Source': 'Metacritic', 'Value': '69/100'}],
 'Released': '04 May 2012',
 'Response': 'True',
 'Runtime': '143 min',
 'Title': 'The Avengers',
 'Type': 'movie',
 'Website': 'N/A',
 'Writer': 'Joss Whedon, Zak Penn',
 'Year': '2012',
 'imdbID': 'tt0848228',
 'imdbRating': '8.0',
 'imdbVotes': '1,547,278'}

In [12]:
import requests
url ="https://www.omdbapi.com/"
params = {
    "apikey":"4d82566d",
    "s":"Avengers", #t 대신 s 사용 -> 제목에 "Avengers" 포함된 영화 전부 검색
    "type":"movie"
}
response = requests.get(url,params=params)
data = response.json()
data

{'Search': [{'Title': 'The Avengers',
   'Year': '2012',
   'imdbID': 'tt0848228',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'Avengers: Endgame',
   'Year': '2019',
   'imdbID': 'tt4154796',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg'},
  {'Title': 'Avengers: Infinity War',
   'Year': '2018',
   'imdbID': 'tt4154756',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg'},
  {'Title': 'Avengers: Age of Ultron',
   'Year': '2015',
   'imdbID': 'tt2395427',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BODBhYTg1NGQtNGVmNS00ZTdiLThjYTYtZDFkNzRiNTZmNDZjXkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'The Avengers',
   'Year': '1998',
   'imdbID': 'tt0118661',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BZTA4ZmZlZWQtZDRlYS00ZWZhLTk0MzEtYjExMGIzMTBlZDNlXkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'Ultimate Avengers: The Movie',
   'Year': '2006',
   'imdbID': 'tt0491703',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTYyMjk0NTMwMl5BMl5BanBnXkFtZTgwNzY0NjAwNzE@._V1_SX300.jpg'},
  {'Title': 'Ultimate Avengers II',
   'Year': '2006',
   'imdbID': 'tt0803093',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BZjI3MTI5ZTYtZmNmNy00OGZmLTlhNWMtNjZiYmYzNDhlOGRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg'},
  {'Title': 'Next Avengers: Heroes of Tomorrow',
   'Year': '2008',
   'imdbID': 'tt1259998',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTQ3NjExNjY4N15BMl5BanBnXkFtZTcwNTczODkwNQ@@._V1_SX300.jpg'},
  {'Title': 'Avengers Confidential: Black Widow & Punisher',
   'Year': '2014',
   'imdbID': 'tt3482378',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTU2MDg0Njk4MF5BMl5BanBnXkFtZTgwMTY0OTIyMTE@._V1_SX300.jpg'},
  {'Title': 'Crippled Avengers',
   'Year': '1978',
   'imdbID': 'tt0077292',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BYjU2ODU5NzMtMzQ2NC00MmI5LWI1NjMtNmRmMjMzOTMxNWZhXkEyXkFqcGc@._V1_SX300.jpg'}],
 'totalResults': '134',
 'Response': 'True'}

In [14]:
#검색 결과 리스트 출력
movies = data["Search"]
for movie in movies:
  print(movie["Title"], movie['Year'])

The Avengers 2012
Avengers: Endgame 2019
Avengers: Infinity War 2018
Avengers: Age of Ultron 2015
The Avengers 1998
Ultimate Avengers: The Movie 2006
Ultimate Avengers II 2006
Next Avengers: Heroes of Tomorrow 2008
Avengers Confidential: Black Widow & Punisher 2014
Crippled Avengers 1978

In [19]:
import pandas as pd
if 'Search' in data:
  m_df = pd.DataFrame(data['Search'])
else:
  m_df = pd.DataFrame([data]) #'Search' 키가 없으면 data 자체가 단일 객체이므로 리스트로 감싸서 DataFrame으로 만든다.

display(m_df.head())

,Title,Year,imdbID,Type,Poster
0,The Avengers,2012,tt0848228,movie,https://m.media-amazon.com/images/M/MV5BNGE0YT...
1,Avengers: Endgame,2019,tt4154796,movie,https://m.media-amazon.com/images/M/MV5BMTc5MD...
2,Avengers: Infinity War,2018,tt4154756,movie,https://m.media-amazon.com/images/M/MV5BMjMxNj...
3,Avengers: Age of Ultron,2015,tt2395427,movie,https://m.media-amazon.com/images/M/MV5BODBhYT...
4,The Avengers,1998,tt0118661,movie,https://m.media-amazon.com/images/M/MV5BZTA4Zm...

In [22]:
m_df = m_df.iloc[0:4] #인덱스 0부터 3까지의 행만 선택
display(m_df)

,Title,Year,imdbID,Type,Poster
0,The Avengers,2012,tt0848228,movie,https://m.media-amazon.com/images/M/MV5BNGE0YT...
1,Avengers: Endgame,2019,tt4154796,movie,https://m.media-amazon.com/images/M/MV5BMTc5MD...
2,Avengers: Infinity War,2018,tt4154756,movie,https://m.media-amazon.com/images/M/MV5BMjMxNj...
3,Avengers: Age of Ultron,2015,tt2395427,movie,https://m.media-amazon.com/images/M/MV5BODBhYT...

In [38]:
#어벤져스 시리즈 4편 정보 수집

#m_df의 'Title'과 'Year' 컬럼 값으로 titles 리스트를 생성
titles = [(row['Title'], row['Year']) for index, row in m_df.iterrows()]
print(titles)
#각 영화 정보를 저장 할 빈 리스트
movies=[]

url = "https://www.omdbapi.com/"
for title, year in titles:
  params = {
    "apikey":"4d82566d",
    "t":title,
    "type":"movie",
    "y":year
  }
  response = requests.get(url,params = params) #RESTful api에서 웹서버에 데이터 요청 get 방식
  data = response.json()
  movies.append({
      "title":data.get('Title'), #파이썬 함수 .get() 메서드를 사용하면 'Title'키가 딕셔너리에 없을 경우 오류 대신 None을 반환
      "year":data.get('Year'),
      "director":data.get('Director'),
      "imdbRating":data.get('imdbRating'),
      "genre":data.get('Genre'),
  })
pprint.pprint(movies)

#데이터 프레임으로 변환
df=pd.DataFrame(movies)
display(df)

[('The Avengers', '2012'), ('Avengers: Endgame', '2019'), ('Avengers: Infinity War', '2018'), ('Avengers: Age of Ultron', '2015')]
[{'director': 'Joss Whedon',
  'genre': 'Action, Sci-Fi',
  'imdbRating': '8.0',
  'title': 'The Avengers',
  'year': '2012'},
 {'director': 'Anthony Russo, Joe Russo',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '8.4',
  'title': 'Avengers: Endgame',
  'year': '2019'},
 {'director': 'Anthony Russo, Joe Russo',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '8.4',
  'title': 'Avengers: Infinity War',
  'year': '2018'},
 {'director': 'Joss Whedon',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '7.3',
  'title': 'Avengers: Age of Ultron',
  'year': '2015'}]

,title,year,director,imdbRating,genre
0,The Avengers,2012,Joss Whedon,8.0,"Action, Sci-Fi"
1,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
2,Avengers: Infinity War,2018,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
3,Avengers: Age of Ultron,2015,Joss Whedon,7.3,"Action, Adventure, Sci-Fi"

In [42]:
df_sorted = df.sort_values(by='imdbRating',ascending=False) #내림차순 정렬
display(df_sorted)
df_sorted2 = df.sort_values(by='year', ascending=False)
display(df_sorted2)

,title,year,director,imdbRating,genre
1,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
2,Avengers: Infinity War,2018,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
0,The Avengers,2012,Joss Whedon,8.0,"Action, Sci-Fi"
3,Avengers: Age of Ultron,2015,Joss Whedon,7.3,"Action, Adventure, Sci-Fi"

,title,year,director,imdbRating,genre
1,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
2,Avengers: Infinity War,2018,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
3,Avengers: Age of Ultron,2015,Joss Whedon,7.3,"Action, Adventure, Sci-Fi"
0,The Avengers,2012,Joss Whedon,8.0,"Action, Sci-Fi"