<a href="https://colab.research.google.com/github/hjiwoong/bigdata/blob/main/dataCollection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("/content/drive/MyDrive/KWU/bigdata/dataCollection/학급당학생수.csv",encoding="EUC-KR")
display(df)

      시점  항목  서울특별시  제주특별자치도
0   2011  전체  29.36    28.88
1   2012  전체  28.63    28.09
2   2013  전체  27.81    27.26
3   2014  전체  26.96    26.46
4   2015  전체  26.19    25.97
5   2016  전체  25.36    25.53
6   2017  전체  24.60    25.25
7   2018  전체  23.76    24.97
8   2019  전체  22.96    24.47
9   2020  전체  22.45    24.15
10  2021  전체  22.47    23.70
11  2022  전체  22.03    23.36
12  2023  전체  21.84    22.72
13  2024  전체  21.77    22.36
14  2025  전체  21.68    21.63

In [9]:
df.head()

     시점  항목  서울특별시  제주특별자치도
0  2011  전체  29.36    28.88
1  2012  전체  28.63    28.09
2  2013  전체  27.81    27.26
3  2014  전체  26.96    26.46
4  2015  전체  26.19    25.97

In [11]:
df.head(10)

     시점  항목  서울특별시  제주특별자치도
0  2011  전체  29.36    28.88
1  2012  전체  28.63    28.09
2  2013  전체  27.81    27.26
3  2014  전체  26.96    26.46
4  2015  전체  26.19    25.97
5  2016  전체  25.36    25.53
6  2017  전체  24.60    25.25
7  2018  전체  23.76    24.97
8  2019  전체  22.96    24.47
9  2020  전체  22.45    24.15

In [13]:
df.tail()

      시점  항목  서울특별시  제주특별자치도
10  2021  전체  22.47    23.70
11  2022  전체  22.03    23.36
12  2023  전체  21.84    22.72
13  2024  전체  21.77    22.36
14  2025  전체  21.68    21.63

In [15]:
df.shape

(15, 4)

In [16]:
car_df=pd.read_csv("/content/drive/MyDrive/KWU/bigdata/dataCollection/자동차표시연비정보.csv")
display(car_df)

,모델명,제조(수입사),차종,유형,복합_연비,1회충전주행거리,도심_연비,고속도로_연비,등급
0,베프(VEV),Luqi Intellgent Technology Co Ltd,화물차,일반형,6,67.0,5.9,6.2,초소형
1,MASADA QQ 2밴,체리자동차,화물차,밴형,6.3,100.0,6.4,6.1,초소형
2,CEVO-C SE 1인승 밴형,주식회사 쎄보모빌리티,승용차,일반형,6.3,69.0,6.7,5.8,초소형
3,포텐스,(주)진우에스엠씨,화물차,일반형,4.5,57.0,5.4,3.8,초소형
4,D2C(D2C13),쎄미시스코,화물차,화물,5.4,79.0,6,4.8,초소형
...,...,...,...,...,...,...,...,...,...
3988,"K7 2.4하이브리드 (17""타이어) (15)",기아,승용차,일반형,16.2,NaN,16.1,16.2,1등급
3989,니로 1.6GDI 하이브리드_18''타이어 (15),기아,승용차,기타형,17.1,NaN,17.7,16.4,1등급
3990,니로 1.6GDI 하이브리드_16''타이어 (15),기아,승용차,기타형,19.5,NaN,20.1,18.7,1등급
3991,아이오닉 1.6GDI 하이브리드 6DCT_17''타이어,현대,승용차,일반형,20.2,NaN,20.4,19.9,1등급
3992,아이오닉 1.6GDI 하이브리드 6DCT_15''타이어,현대,승용차,일반형,22.4,NaN,22.5,22.2,1등급

In [23]:
display(car_df.head())

,모델명,제조(수입사),차종,유형,복합_연비,1회충전주행거리,도심_연비,고속도로_연비,등급
0,베프(VEV),Luqi Intellgent Technology Co Ltd,화물차,일반형,6,67.0,5.9,6.2,초소형
1,MASADA QQ 2밴,체리자동차,화물차,밴형,6.3,100.0,6.4,6.1,초소형
2,CEVO-C SE 1인승 밴형,주식회사 쎄보모빌리티,승용차,일반형,6.3,69.0,6.7,5.8,초소형
3,포텐스,(주)진우에스엠씨,화물차,일반형,4.5,57.0,5.4,3.8,초소형
4,D2C(D2C13),쎄미시스코,화물차,화물,5.4,79.0,6,4.8,초소형

In [24]:
display(car_df.tail())

,모델명,제조(수입사),차종,유형,복합_연비,1회충전주행거리,도심_연비,고속도로_연비,등급
3988,"K7 2.4하이브리드 (17""타이어) (15)",기아,승용차,일반형,16.2,NaN,16.1,16.2,1등급
3989,니로 1.6GDI 하이브리드_18''타이어 (15),기아,승용차,기타형,17.1,NaN,17.7,16.4,1등급
3990,니로 1.6GDI 하이브리드_16''타이어 (15),기아,승용차,기타형,19.5,NaN,20.1,18.7,1등급
3991,아이오닉 1.6GDI 하이브리드 6DCT_17''타이어,현대,승용차,일반형,20.2,NaN,20.4,19.9,1등급
3992,아이오닉 1.6GDI 하이브리드 6DCT_15''타이어,현대,승용차,일반형,22.4,NaN,22.5,22.2,1등급

In [25]:
car_df.shape

(3993, 9)

In [26]:
display(car_df.describe())

         1회충전주행거리
count  606.000000
mean   307.240264
std    163.880204
min      7.000000
25%    153.000000
50%    370.500000
75%    437.750000
max    739.000000