<a href="https://colab.research.google.com/github/hjiwoong/bigdata/blob/main/pandas_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd

In [35]:
scientists = pd.read_csv("/content/drive/MyDrive/KWU/bigdata/pandas_ex/data/scientists.csv")

In [36]:
display(scientists)

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [37]:
names=scientists['Name']
print(names)

0       Rosaline Franklin
1          William Gosset
2    Florence Nightingale
3             Marie Curie
4           Rachel Carson
5               John Snow
6             Alan Turing
7            Johann Gauss
Name: Name, dtype: object

### pickle 파일 저장하고 불러오기
- 파이썬 프로그램에서 생성한 어떤 객체(예: 리스트, 딕셔너리, pandas DataFrame, Series등)의 구조와 데이터를 그대로 파일로 저장하고 싶을 때 pickle모듈을 사용
- 피클(pickle)은 파이썬 객체 그 자체를 통째로 얼려서 파일로 저장하는 기술
- 머신러닝 모델 학습이 완료된 모델 객체를 피클로 저장
- 저장된 피클 파일만 불러오면 바로 예측 predict을 할 수 있다.
- 머신러닝 모델 내부의 가중치와 설정값이 그대로 유지

In [38]:
names.to_pickle("/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_names_series.pickle")

In [39]:
scientists.to_pickle("/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_df.pickle")

In [40]:
series_pickle=pd.read_pickle("/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_names_series.pickle")
print(series_pickle)

0       Rosaline Franklin
1          William Gosset
2    Florence Nightingale
3             Marie Curie
4           Rachel Carson
5               John Snow
6             Alan Turing
7            Johann Gauss
Name: Name, dtype: object

In [41]:
dataframe_pickle=pd.read_pickle("/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_df.pickle")
display(dataframe_pickle)

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

### CSV와 TSV파일로 저장하고 불러오기

In [42]:
scientists.to_csv("/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_df_no_index.csv",index=False)

### 엑셀로 저장하기

In [43]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [44]:
names=scientists.set_index('Name')['Occupation']
print(names)
print(type(names))

Name
Rosaline Franklin                  Chemist
William Gosset                Statistician
Florence Nightingale                 Nurse
Marie Curie                        Chemist
Rachel Carson                    Biologist
John Snow                        Physician
Alan Turing             Computer Scientist
Johann Gauss                 Mathematician
Name: Occupation, dtype: object
<class 'pandas.core.series.Series'>

In [45]:
names_df=names.to_frame() #시리즈를 데이터프레임으로 변환

In [46]:
print(names_df)
print(type(names_df))

                              Occupation
Name
Rosaline Franklin                Chemist
William Gosset              Statistician
Florence Nightingale               Nurse
Marie Curie                      Chemist
Rachel Carson                  Biologist
John Snow                      Physician
Alan Turing           Computer Scientist
Johann Gauss               Mathematician
<class 'pandas.core.frame.DataFrame'>

In [47]:
names_df.to_excel('/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_names_series_df.xls',engine='openpyxl')

In [48]:
scientists.to_excel('/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_df.xlsx',sheet_name='scientist',index=False)

### feather 파일로 저장하기
- feather 파일은 pandas 데이터프레임을 빠르고 효율적으로 저장하기 위한 파일

In [49]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [50]:
scientists.to_feather("/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_df.feather")

In [51]:
sci_feather=pd.read_feather("/content/drive/MyDrive/KWU/bigdata/pandas_ex/output/scientists_df.feather")
display(sci_feather)

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

### 딕셔너리로 변환하기

In [53]:
sci_sub_dict = scientists.head(2)

In [55]:
sci_dict=sci_sub_dict.to_dict()

In [57]:
print(sci_dict)

{'Name': {0: 'Rosaline Franklin', 1: 'William Gosset'}, 'Born': {0: '1920-07-25', 1: '1876-06-13'}, 'Died': {0: '1958-04-16', 1: '1937-10-16'}, 'Age': {0: 37, 1: 61}, 'Occupation': {0: 'Chemist', 1: 'Statistician'}}

In [59]:
import pprint
pprint.pprint(sci_dict) #딕셔너리

{'Age': {0: 37, 1: 61},
 'Born': {0: '1920-07-25', 1: '1876-06-13'},
 'Died': {0: '1958-04-16', 1: '1937-10-16'},
 'Name': {0: 'Rosaline Franklin', 1: 'William Gosset'},
 'Occupation': {0: 'Chemist', 1: 'Statistician'}}

In [61]:
sci_dict_df=pd.DataFrame.from_dict(sci_dict)
display(sci_dict_df)

                Name        Born        Died  Age    Occupation
0  Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1     William Gosset  1876-06-13  1937-10-16   61  Statistician

### JSON 파일로 저장하기
```
#객체(딕셔너리와 유사) - 중괄호 사용, 키와 값은 큰 따옴표로 감싸기
{"title":"어벤져스","year":2012}

#배열(리스트와 유사) - 대괄호 사용
{"director":["조스 웨던","앤서니 루소"]}

#중첩 구조 - 여러 객체를 배열로 묶기
[
  {"title":"어벤져스", "year":2012},
  {"title":"어벤져스:엔드게임", "year":2019}
]
```

In [64]:
import json

In [72]:
d={"title":"어벤져스", "year":2012}
#딕셔너리 -> JSON 문자열로 변환
d_str = json.dumps(d)
type(d_str)

str

In [73]:
print(d_str)

{"title": "\uc5b4\ubca4\uc838\uc2a4", "year": 2012}

In [70]:
#JSON문자열 -> 파이썬 딕셔너리로 변환
d2 = json.loads(d_str)
print(d2)

{'title': '어벤져스', 'year': 2012}

In [75]:
print(d2['title'])

어벤져스

In [78]:
#세겹 따옴표(""")로 여러 줄 문자열 작성
d3_str = """
{
  "title":"어벤져스",
  "director":["조스 웨던"],
  "year":2012
}
"""
d3 = json.loads(d3_str) #JSON 문자열 -> 파이썬 딕셔너리로 변환

In [80]:
d3

{'title': '어벤져스', 'director': ['조스 웨던'], 'year': 2012}

In [85]:
#JSON 문자열(배열구조)을 데이터프레임으로 변환
df=pd.read_json(d3_str)
df

/tmp/ipykernel_1519/3725150304.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_json(d3_str)

  title director  year
0  어벤져스    조스 웨던  2012

In [87]:
df = pd.DataFrame(json.loads(d3_str)) #또는 파이썬 딕셔너리 객체를 DataFrame 클래스로 변환
df

  title director  year
0  어벤져스    조스 웨던  2012

### JSON으로 저장하기

In [91]:
sci_json=sci_sub_dict.to_json(orient='records',indent=2,date_format="iso")
pprint.pprint(sci_json)
#pandas 데이터프레임을 json문자열로 변환
#orient='records'는 데이터프레임의 각 행을 하나의 json객체로 변환하고 리스트에 담는 형식
#indent는 들여쓰기
#date_format는 날짜/시간 정보, "iso"는 표준화된 방식으로 표현

('[\n'
 '  {\n'
 '    "Name":"Rosaline Franklin",\n'
 '    "Born":"1920-07-25",\n'
 '    "Died":"1958-04-16",\n'
 '    "Age":37,\n'
 '    "Occupation":"Chemist"\n'
 '  },\n'
 '  {\n'
 '    "Name":"William Gosset",\n'
 '    "Born":"1876-06-13",\n'
 '    "Died":"1937-10-16",\n'
 '    "Age":61,\n'
 '    "Occupation":"Statistician"\n'
 '  }\n'
 ']')

In [93]:
sci_json_df = pd.read_json(
    ('[\n'
 '  {\n'
 '    "Name":"Rosaline Franklin",\n'
 '    "Born":"1920-07-25",\n'
 '    "Died":"1958-04-16",\n'
 '    "Age":37,\n'
 '    "Occupation":"Chemist"\n'
 '  },\n'
 '  {\n'
 '    "Name":"William Gosset",\n'
 '    "Born":"1876-06-13",\n'
 '    "Died":"1937-10-16",\n'
 '    "Age":61,\n'
 '    "Occupation":"Statistician"\n'
 '  }\n'
 ']'),
    orient='records'
)

/tmp/ipykernel_1519/3581717962.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  sci_json_df = pd.read_json(

In [94]:
display(sci_json_df)

                Name        Born        Died  Age    Occupation
0  Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1     William Gosset  1876-06-13  1937-10-16   61  Statistician

In [96]:
display(sci_json_df.dtypes)

Name          object
Born          object
Died          object
Age            int64
Occupation    object
dtype: object