<a href="https://colab.research.google.com/github/hjiwoong/bigdata/blob/main/pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"name":["kim","lee","park","choi","na"],
                   "test": [45, 30, 40, 37, 48],
                   "kor": [20,17,22,18,24],
                   "eng": [19,14,18,15,25]})

In [3]:
display(df)
print(df)

   name  test  kor  eng
0   kim    45   20   19
1   lee    30   17   14
2  park    40   22   18
3  choi    37   18   15
4    na    48   24   25

   name  test  kor  eng
0   kim    45   20   19
1   lee    30   17   14
2  park    40   22   18
3  choi    37   18   15
4    na    48   24   25

In [4]:
df = pd.DataFrame([["kim",45,20,19],
                   ["lee",30,17,14],
                   ["park",40,22,18],
                   ["choi",37,18,15],
                   ["na",48,24,25]],
                  columns=["name","test","kor","eng"])
display(df)

   name  test  kor  eng
0   kim    45   20   19
1   lee    30   17   14
2  park    40   22   18
3  choi    37   18   15
4    na    48   24   25

In [5]:
df=pd.DataFrame()
df["name"]=["kim","lee","park","choi","na"]
df["test"]=[45,30,40,37,48]
df["kor"]=[20,17,22,18,24]
df["eng"]=[19,14,18,15,25]
df["math"]=[10,20,30,40,50]
display(df)

   name  test  kor  eng  math
0   kim    45   20   19    10
1   lee    30   17   14    20
2  park    40   22   18    30
3  choi    37   18   15    40
4    na    48   24   25    50

In [6]:
display(df["math"]) #인덱스 번호와 값만 존재하는 1차원 배열 "시리즈"

0    10
1    20
2    30
3    40
4    50
Name: math, dtype: int64

In [7]:
display(df[["math","name"]]) #2차원 배열 "데이터프레임"은 대괄호 두개 사용

   math  name
0    10   kim
1    20   lee
2    30  park
3    40  choi
4    50    na

In [8]:
n=df.pop("math")

In [9]:
display(n)
display(df)

0    10
1    20
2    30
3    40
4    50
Name: math, dtype: int64

   name  test  kor  eng
0   kim    45   20   19
1   lee    30   17   14
2  park    40   22   18
3  choi    37   18   15
4    na    48   24   25

In [10]:
for index, row in df.iterrows():
  print(index, row["name"], row["test"])

0 kim 45
1 lee 30
2 park 40
3 choi 37
4 na 48

In [11]:
df["sum"]=df["test"]+df["kor"]+df["eng"]
display(df)

   name  test  kor  eng  sum
0   kim    45   20   19   84
1   lee    30   17   14   61
2  park    40   22   18   80
3  choi    37   18   15   70
4    na    48   24   25   97

In [12]:
display(df[df["sum"]>=80]) #조건을 만족하는 데이터 행을 추출

   name  test  kor  eng  sum
0   kim    45   20   19   84
2  park    40   22   18   80
4    na    48   24   25   97

In [13]:
print(df["sum"]>=80)

0     True
1    False
2     True
3    False
4     True
Name: sum, dtype: bool

In [14]:
display(df[df["sum"]>=80][["name", "sum"]])

   name  sum
0   kim   84
2  park   80
4    na   97

In [15]:
df = pd.read_csv("/content/drive/MyDrive/KWU/bigdata/pandas_ex/data/gapminder.tsv",sep="\t")

In [16]:
display(df)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [17]:
df.shape

(1704, 6)

In [18]:
display(type(df))
print("\n")
display(df.columns)
print("\n")
display(df.dtypes)
print("\n")
display(df.info())
print("\n")
display(df.head())

pandas.core.frame.DataFrame

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

None

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [23]:
#행과 열을 함께 지정하여 추출
display(df.loc[42,'country']) #loc[행이름,열이름]

'Angola'

In [20]:
print(df.iloc[42,0]) #iloc[행 인덱스, 열인덱스]

Angola

In [25]:
#여러 행과 열 지정하여 데이터 추출하기
display(df.loc[[0,99,999],['country','lifeExp','gdpPercap']])

         country  lifeExp    gdpPercap
0    Afghanistan   28.801   779.445314
99    Bangladesh   43.453   721.186086
999     Mongolia   51.253  1226.041130

In [26]:
display(df.iloc[[0,99,999],[0,3,5]])

         country  lifeExp    gdpPercap
0    Afghanistan   28.801   779.445314
99    Bangladesh   43.453   721.186086
999     Mongolia   51.253  1226.041130

In [27]:
#기초통계
display(df)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [33]:
display(df.groupby('year')['lifeExp'].mean())

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [40]:
#2개 이상 열 그룹화 하기
multi_group_var = df.groupby(['year','continent'])[['lifeExp','gdpPercap']].mean()
display(multi_group_var)
#year continent는 멀티 인덱스

                  lifeExp     gdpPercap
year continent
1952 Africa     39.135500   1252.572466
     Americas   53.279840   4079.062552
     Asia       46.314394   5195.484004
     Europe     64.408500   5661.057435
     Oceania    69.255000  10298.085650
1957 Africa     41.266346   1385.236062
     Americas   55.960280   4616.043733
     Asia       49.318544   5787.732940
     Europe     66.703067   6963.012816
     Oceania    70.295000  11598.522455
1962 Africa     43.319442   1598.078825
     Americas   58.398760   4901.541870
     Asia       51.563223   5729.369625
     Europe     68.539233   8365.486814
     Oceania    71.085000  12696.452430
1967 Africa     45.334538   2050.363801
     Americas   60.410920   5668.253496
     Asia       54.663640   5971.173374
     Europe     69.737600  10143.823757
     Oceania    71.310000  14495.021790
1972 Africa     47.450942   2339.615674
     Americas   62.394920   6491.334139
     Asia       57.319269   8187.468699
     Europe     70.775033  12479.575246
     Oceania    71.910000  16417.333380
1977 Africa     49.580423   2585.938508
     Americas   64.391560   7352.007126
     Asia       59.610556   7791.314020
     Europe     71.937767  14283.979110
     Oceania    72.855000  17283.957605
1982 Africa     51.592865   2481.592960
     Americas   66.228840   7506.737088
     Asia       62.617939   7434.135157
     Europe     72.806400  15617.896551
     Oceania    74.290000  18554.709840
1987 Africa     53.344788   2282.668991
     Americas   68.090720   7793.400261
     Asia       64.851182   7608.226508
     Europe     73.642167  17214.310727
     Oceania    75.320000  20448.040160
1992 Africa     53.629577   2281.810333
     Americas   69.568360   8044.934406
     Asia       66.537212   8639.690248
     Europe     74.440100  17061.568084
     Oceania    76.945000  20894.045885
1997 Africa     53.598269   2378.759555
     Americas   71.150480   8889.300863
     Asia       68.020515   9834.093295
     Europe     75.505167  19076.781802
     Oceania    78.190000  24024.175170
2002 Africa     53.325231   2599.385159
     Americas   72.422040   9287.677107
     Asia       69.233879  10174.090397
     Europe     76.700600  21711.732422
     Oceania    79.740000  26938.778040
2007 Africa     54.806038   3089.032605
     Americas   73.608120  11003.031625
     Asia       70.728485  12473.026870
     Europe     77.648600  25054.481636
     Oceania    80.719500  29810.188275

In [41]:
flat=multi_group_var.reset_index() #기존 멀티 인덱스였던 year.continent가 일반 열로 바뀌고 새로운 0부터 시작하는 인덱스 생성
display(flat)

    year continent    lifeExp     gdpPercap
0   1952    Africa  39.135500   1252.572466
1   1952  Americas  53.279840   4079.062552
2   1952      Asia  46.314394   5195.484004
3   1952    Europe  64.408500   5661.057435
4   1952   Oceania  69.255000  10298.085650
5   1957    Africa  41.266346   1385.236062
6   1957  Americas  55.960280   4616.043733
7   1957      Asia  49.318544   5787.732940
8   1957    Europe  66.703067   6963.012816
9   1957   Oceania  70.295000  11598.522455
10  1962    Africa  43.319442   1598.078825
11  1962  Americas  58.398760   4901.541870
12  1962      Asia  51.563223   5729.369625
13  1962    Europe  68.539233   8365.486814
14  1962   Oceania  71.085000  12696.452430
15  1967    Africa  45.334538   2050.363801
16  1967  Americas  60.410920   5668.253496
17  1967      Asia  54.663640   5971.173374
18  1967    Europe  69.737600  10143.823757
19  1967   Oceania  71.310000  14495.021790
20  1972    Africa  47.450942   2339.615674
21  1972  Americas  62.394920   6491.334139
22  1972      Asia  57.319269   8187.468699
23  1972    Europe  70.775033  12479.575246
24  1972   Oceania  71.910000  16417.333380
25  1977    Africa  49.580423   2585.938508
26  1977  Americas  64.391560   7352.007126
27  1977      Asia  59.610556   7791.314020
28  1977    Europe  71.937767  14283.979110
29  1977   Oceania  72.855000  17283.957605
30  1982    Africa  51.592865   2481.592960
31  1982  Americas  66.228840   7506.737088
32  1982      Asia  62.617939   7434.135157
33  1982    Europe  72.806400  15617.896551
34  1982   Oceania  74.290000  18554.709840
35  1987    Africa  53.344788   2282.668991
36  1987  Americas  68.090720   7793.400261
37  1987      Asia  64.851182   7608.226508
38  1987    Europe  73.642167  17214.310727
39  1987   Oceania  75.320000  20448.040160
40  1992    Africa  53.629577   2281.810333
41  1992  Americas  69.568360   8044.934406
42  1992      Asia  66.537212   8639.690248
43  1992    Europe  74.440100  17061.568084
44  1992   Oceania  76.945000  20894.045885
45  1997    Africa  53.598269   2378.759555
46  1997  Americas  71.150480   8889.300863
47  1997      Asia  68.020515   9834.093295
48  1997    Europe  75.505167  19076.781802
49  1997   Oceania  78.190000  24024.175170
50  2002    Africa  53.325231   2599.385159
51  2002  Americas  72.422040   9287.677107
52  2002      Asia  69.233879  10174.090397
53  2002    Europe  76.700600  21711.732422
54  2002   Oceania  79.740000  26938.778040
55  2007    Africa  54.806038   3089.032605
56  2007  Americas  73.608120  11003.031625
57  2007      Asia  70.728485  12473.026870
58  2007    Europe  77.648600  25054.481636
59  2007   Oceania  80.719500  29810.188275

In [43]:
#그룹화한 데이터 개수 구하기
print(df.groupby('continent')['country'].nunique())
#Series나 DataFrame에서 고유한(unique) 값들의 개수를 반환. 각 대륙별로 고유한 국가의 개수를 계산

continent
Africa      52
Americas    25
Asia        33
Europe      30
Oceania      2
Name: country, dtype: int64

In [47]:
print(df.groupby('continent')['country'].value_counts())
#선택된 'country'열에서 각 대륙별로 각 국가가 몇번 나타나는지를 계산
#Series 형태로 반환하고 가장 빈도가 높은 값부터 내림차순으로 정렬
#Series 내의 고유한 값들과 각 값의 출현 빈도를 계산

continent  country
Africa     Algeria           12
           Angola            12
           Benin             12
           Botswana          12
           Burkina Faso      12
                             ..
Europe     Switzerland       12
           Turkey            12
           United Kingdom    12
Oceania    Australia         12
           New Zealand       12
Name: count, Length: 142, dtype: int64

In [54]:
s=df.groupby('continent')['country'].value_counts()
print(type(s))

<class 'pandas.core.series.Series'>