<a href="https://colab.research.google.com/github/hjiwoong/bigdata/blob/main/pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
df = pd.DataFrame({"name":["kim","lee","park","choi","na"],
                   "test": [45, 30, 40, 37, 48],
                   "kor": [20,17,22,18,24],
                   "eng": [19,14,18,15,25]})

In [7]:
display(df)
print(df)

   name  test  kor  eng
0   kim    45   20   19
1   lee    30   17   14
2  park    40   22   18
3  choi    37   18   15
4    na    48   24   25

   name  test  kor  eng
0   kim    45   20   19
1   lee    30   17   14
2  park    40   22   18
3  choi    37   18   15
4    na    48   24   25

In [47]:
df = pd.DataFrame([["kim",45,20,19],
                   ["lee",30,17,14],
                   ["park",40,22,18],
                   ["choi",37,18,15],
                   ["na",48,24,25]],
                  columns=["name","test","kor","eng"])
display(df)

   name  test  kor  eng
0   kim    45   20   19
1   lee    30   17   14
2  park    40   22   18
3  choi    37   18   15
4    na    48   24   25

In [72]:
df=pd.DataFrame()
df["name"]=["kim","lee","park","choi","na"]
df["test"]=[45,30,40,37,48]
df["kor"]=[20,17,22,18,24]
df["eng"]=[19,14,18,15,25]
df["math"]=[10,20,30,40,50]
display(df)

   name  test  kor  eng  math
0   kim    45   20   19    10
1   lee    30   17   14    20
2  park    40   22   18    30
3  choi    37   18   15    40
4    na    48   24   25    50

In [73]:
display(df["math"]) #인덱스 번호와 값만 존재하는 1차원 배열 "시리즈"

0    10
1    20
2    30
3    40
4    50
Name: math, dtype: int64

In [74]:
display(df[["math","name"]]) #2차원 배열 "데이터프레임"은 대괄호 두개 사용

   math  name
0    10   kim
1    20   lee
2    30  park
3    40  choi
4    50    na

In [75]:
n=df.pop("math")

In [77]:
display(n)
display(df)

0    10
1    20
2    30
3    40
4    50
Name: math, dtype: int64

   name  test  kor  eng
0   kim    45   20   19
1   lee    30   17   14
2  park    40   22   18
3  choi    37   18   15
4    na    48   24   25

In [78]:
for index, row in df.iterrows():
  print(index, row["name"], row["test"])

0 kim 45
1 lee 30
2 park 40
3 choi 37
4 na 48

In [80]:
df["sum"]=df["test"]+df["kor"]+df["eng"]
display(df)

   name  test  kor  eng  sum
0   kim    45   20   19   84
1   lee    30   17   14   61
2  park    40   22   18   80
3  choi    37   18   15   70
4    na    48   24   25   97

In [84]:
display(df[df["sum"]>=80]) #조건을 만족하는 데이터 행을 추출

   name  test  kor  eng  sum
0   kim    45   20   19   84
2  park    40   22   18   80
4    na    48   24   25   97

In [86]:
print(df["sum"]>=80)

0     True
1    False
2     True
3    False
4     True
Name: sum, dtype: bool

In [91]:
display(df[df["sum"]>=80][["name", "sum"]])

   name  sum
0   kim   84
2  park   80
4    na   97

In [95]:
df = pd.read_csv("/content/drive/MyDrive/KWU/bigdata/pandas_ex/data/gapminder.tsv",sep="\t")

In [97]:
display(df)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [101]:
df.shape

(1704, 6)

In [113]:
display(type(df))
print("\n")
display(df.columns)
print("\n")
display(df.dtypes)
print("\n")
display(df.info())
print("\n")
display(df.head())

pandas.core.frame.DataFrame

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

None

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106