<a href="https://colab.research.google.com/github/hjiwoong/bigdata/blob/main/pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Series 시리즈와 DataFrame 데이터 프레임

In [401]:
import pandas as pd

In [402]:
#시리즈 만들기
s=pd.Series(['apple','banana']) #파이썬 리스트(list)를 pd.Series()함수에 전달하면, 리스트 각 요소가 시리즈의 데이터가 된다
display(s)

0     apple
1    banana
dtype: object

In [403]:
s=pd.Series(data=['Wes McKinney','Creator of Pandas'],index=['Person','Who'])
display(s)

Person         Wes McKinney
Who       Creator of Pandas
dtype: object

In [404]:
#데이터프레임 만들기
scientists=pd.DataFrame({
    "Name":["Rosaline Franklin","William Gosset"],
    "Occupation":["Chemist","Statistician"],
    "Born":["1920-07-25", "1876-06-13"],
    "Died":["1958-04-16","1937-10-16"],
    "Age":[37,61]
})
display(scientists)

                Name    Occupation        Born        Died  Age
0  Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
1     William Gosset  Statistician  1876-06-13  1937-10-16   61

In [405]:
scientists=pd.DataFrame(
    data={
    "Occupation":["Chemist","Statistician"],
    "Born":["1920-07-25", "1876-06-13"],
    "Died":["1958-04-16","1937-10-16"],
    "Age":[37,61]
    },
    index=["Rosaline Franklin","William Gosset"],
    columns=["Occupation","Born","Died","Age"])
display(scientists)

                     Occupation        Born        Died  Age
Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
William Gosset     Statistician  1876-06-13  1937-10-16   61

In [406]:
first_row=scientists.loc['William Gosset']
print(type(first_row))
print(first_row) #인덱스와 값으로 이루어진 시리즈

<class 'pandas.core.series.Series'>
Occupation    Statistician
Born            1876-06-13
Died            1937-10-16
Age                     61
Name: William Gosset, dtype: object

In [407]:
print(first_row.index)

Index(['Occupation', 'Born', 'Died', 'Age'], dtype='object')

In [408]:
#시리즈의 Keys() 메서드 : 인덱스의 목록 반환
#데이터프레임의 keys() 메서드 : 키 목록 반환
print(first_row.keys())

Index(['Occupation', 'Born', 'Died', 'Age'], dtype='object')

In [409]:
print(first_row.index[0])

Occupation

In [410]:
print(first_row.keys()[0])

Occupation

In [411]:
scientists

                     Occupation        Born        Died  Age
Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
William Gosset     Statistician  1876-06-13  1937-10-16   61

In [412]:
print(type(scientists))

<class 'pandas.core.frame.DataFrame'>

In [413]:
ages=scientists['Age']
display(ages)

Rosaline Franklin    37
William Gosset       61
Name: Age, dtype: int64

In [414]:
print(type(ages))

<class 'pandas.core.series.Series'>

In [415]:
print(ages.mean())

49.0

In [416]:
print(ages.min())

37

In [417]:
print(ages.max())

61

In [418]:
print(ages.std())

16.97056274847714

In [419]:
scientists=pd.read_csv("/content/drive/MyDrive/KWU/bigdata/pandas_ex/data/scientists.csv")

In [420]:
display(scientists)
display(scientists.describe())
display(scientists.info())

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

             Age
count   8.000000
mean   59.125000
std    18.325918
min    37.000000
25%    44.000000
50%    58.500000
75%    68.750000
max    90.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Born        8 non-null      object
 2   Died        8 non-null      object
 3   Age         8 non-null      int64
 4   Occupation  8 non-null      object
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes

None

In [421]:
ages=scientists['Age']
display(ages)

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [422]:
print(ages.describe())

count     8.000000
mean     59.125000
std      18.325918
min      37.000000
25%      44.000000
50%      58.500000
75%      68.750000
max      90.000000
Name: Age, dtype: float64

In [423]:
print(ages.mean())

59.125

In [424]:
print(ages[ages>ages.mean()]) #True에 해당되는 것만 리스트로 반환

1    61
2    90
3    66
7    77
Name: Age, dtype: int64

In [425]:
print(ages>ages.mean())

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

In [426]:
print(type(ages>ages.mean()))

<class 'pandas.core.series.Series'>

### 벡터와 스칼라
- 벡터(vector): 순서가 있는 여러개의 값들의 집합을 의미. 수학적으로는 1차원 배열
- pandas에서는 시리즈(Series)가 백터이다.
- 스칼라(Scalar): 하나의 단일 값을 의미

In [427]:
display(ages)
print(type(ages))

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

<class 'pandas.core.series.Series'>

In [428]:
print(ages+ages)

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [429]:
print(ages*ages)

0    1369
1    3721
2    8100
3    4356
4    3136
5    2025
6    1681
7    5929
Name: Age, dtype: int64

In [430]:
print(ages+100) #백터+스칼라

0    137
1    161
2    190
3    166
4    156
5    145
6    141
7    177
Name: Age, dtype: int64

In [431]:
print(ages*2)

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [432]:
#길이가 서로 다른 벡터 연산하기
print(ages+pd.Series([1,100])) #오류는 안나지만 NaN

0     38.0
1    161.0
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [433]:
import numpy as np

In [434]:
#print(ages + np.array([1,100])) #길이가 맞지 않아 오류 발생

In [435]:
#인덱스가 같은 벡터 자동 정렬하기
rev_ages=ages.sort_index(ascending=False) #내림차순
display(rev_ages)

7    77
6    41
5    45
4    56
3    66
2    90
1    61
0    37
Name: Age, dtype: int64

In [436]:
print(ages+rev_ages) #같은 인덱스 값을 계산

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

### 데이터 프레임

In [437]:
display(scientists)

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [438]:
scientists.index

RangeIndex(start=0, stop=8, step=1)

In [439]:
scientists.columns

Index(['Name', 'Born', 'Died', 'Age', 'Occupation'], dtype='object')

In [440]:
scientists.values

array([['Rosaline Franklin', '1920-07-25', '1958-04-16', 37, 'Chemist'],
       ['William Gosset', '1876-06-13', '1937-10-16', 61, 'Statistician'],
       ['Florence Nightingale', '1820-05-12', '1910-08-13', 90, 'Nurse'],
       ['Marie Curie', '1867-11-07', '1934-07-04', 66, 'Chemist'],
       ['Rachel Carson', '1907-05-27', '1964-04-14', 56, 'Biologist'],
       ['John Snow', '1813-03-15', '1858-06-16', 45, 'Physician'],
       ['Alan Turing', '1912-06-23', '1954-06-07', 41,
        'Computer Scientist'],
       ['Johann Gauss', '1777-04-30', '1855-02-23', 77, 'Mathematician']],
      dtype=object)

In [441]:
print(scientists['Age'].mean())

59.125

In [442]:
print(scientists.loc[scientists['Age']>scientists['Age'].mean()]) #True에 해당되는 행만 보여줌

                   Name        Born        Died  Age     Occupation
1        William Gosset  1876-06-13  1937-10-16   61   Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

In [443]:
#데이터 프레임으로 연산하기
first_half=scientists[:4] #0:4직전 행만 출력
second_half=scientists[4:] #4:끝까지 행 출력
print(first_half)
print(second_half)

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
            Name        Born        Died  Age          Occupation
4  Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5      John Snow  1813-03-15  1858-06-16   45           Physician
6    Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7   Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [444]:
print(scientists*2) #각 값에 2배 곱하기

                                       Name                  Born  \
0        Rosaline FranklinRosaline Franklin  1920-07-251920-07-25
1              William GossetWilliam Gosset  1876-06-131876-06-13
2  Florence NightingaleFlorence Nightingale  1820-05-121820-05-12
3                    Marie CurieMarie Curie  1867-11-071867-11-07
4                Rachel CarsonRachel Carson  1907-05-271907-05-27
5                        John SnowJohn Snow  1813-03-151813-03-15
6                    Alan TuringAlan Turing  1912-06-231912-06-23
7                  Johann GaussJohann Gauss  1777-04-301777-04-30

                   Died  Age                            Occupation
0  1958-04-161958-04-16   74                        ChemistChemist
1  1937-10-161937-10-16  122              StatisticianStatistician
2  1910-08-131910-08-13  180                            NurseNurse
3  1934-07-041934-07-04  132                        ChemistChemist
4  1964-04-141964-04-14  112                    BiologistBiologist
5  1858-06-161858-06-16   90                    PhysicianPhysician
6  1954-06-071954-06-07   82  Computer ScientistComputer Scientist
7  1855-02-231855-02-23  154            MathematicianMathematician

In [445]:
df1=df2=pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]])
display(df1)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [446]:
df_added=df1.add(df2)
display(df_added)

    0   1   2
0   2   4   6
1   8  10  12
2  14  16  18

### 시리즈와 데이터프레임 데이터 변경하기

In [447]:
print(scientists.dtypes)

Name          object
Born          object
Died          object
Age            int64
Occupation    object
dtype: object

In [448]:
born_datetime=pd.to_datetime(scientists['Born'],format='%Y-%m-%d')
print(born_datetime)

0   1920-07-25
1   1876-06-13
2   1820-05-12
3   1867-11-07
4   1907-05-27
5   1813-03-15
6   1912-06-23
7   1777-04-30
Name: Born, dtype: datetime64[ns]

In [449]:
died_datetime=pd.to_datetime(scientists['Died'],format='%Y-%m-%d')
print(died_datetime)

0   1958-04-16
1   1937-10-16
2   1910-08-13
3   1934-07-04
4   1964-04-14
5   1858-06-16
6   1954-06-07
7   1855-02-23
Name: Died, dtype: datetime64[ns]

In [450]:
scientists['born_dt'],scientists['died_dt']=(born_datetime, died_datetime)

In [451]:
display(scientists)

,Name,Born,Died,Age,Occupation,born_dt,died_dt
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,1920-07-25,1958-04-16
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,1820-05-12,1910-08-13
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,1867-11-07,1934-07-04
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,1907-05-27,1964-04-14
5,John Snow,1813-03-15,1858-06-16,45,Physician,1813-03-15,1858-06-16
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,1912-06-23,1954-06-07
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,1777-04-30,1855-02-23

In [452]:
display(scientists.dtypes)
display(scientists.shape)

Name                  object
Born                  object
Died                  object
Age                    int64
Occupation            object
born_dt       datetime64[ns]
died_dt       datetime64[ns]
dtype: object

(8, 7)

### 열 내용 변경하기

In [453]:
print(scientists['Age'])

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [454]:
print(scientists['Age'].sample(frac=1,random_state=42))
#frac=1 , frac인자는 샘플링할 비율을 지정, 전체데이터(100%)를 샘플링하겠다는 의미, 모든 데이터를 포함하되 순서만 무작위로 섞는 셔플링 효과를 준다.
#random_state 인자는 난수 생성기의 시드(seed)를 설정, 이 값을 지정하면 코드를 여러번 실행해도 항상 동일한 순서로 데이터가 섞이게 된다. 결과의 재현성을 보장

1    61
5    45
0    37
7    77
2    90
4    56
3    66
6    41
Name: Age, dtype: int64

In [455]:
scientists["Age"]=scientists["Age"].sample(frac=1,random_state=42) #섞기 전과 동일
print(scientists["Age"])

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [456]:
scientists['Age'] = scientists['Age'].sample(frac=1, random_state=42).values
print(scientists['Age'])

0    61
1    45
2    37
3    77
4    90
5    56
6    66
7    41
Name: Age, dtype: int64

In [457]:
scientists['age_days']=(scientists['died_dt']-scientists['born_dt'])
display(scientists)

,Name,Born,Died,Age,Occupation,born_dt,died_dt,age_days
0,Rosaline Franklin,1920-07-25,1958-04-16,61,Chemist,1920-07-25,1958-04-16,13779 days
1,William Gosset,1876-06-13,1937-10-16,45,Statistician,1876-06-13,1937-10-16,22404 days
2,Florence Nightingale,1820-05-12,1910-08-13,37,Nurse,1820-05-12,1910-08-13,32964 days
3,Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days
4,Rachel Carson,1907-05-27,1964-04-14,90,Biologist,1907-05-27,1964-04-14,20777 days
5,John Snow,1813-03-15,1858-06-16,56,Physician,1813-03-15,1858-06-16,16529 days
6,Alan Turing,1912-06-23,1954-06-07,66,Computer Scientist,1912-06-23,1954-06-07,15324 days
7,Johann Gauss,1777-04-30,1855-02-23,41,Mathematician,1777-04-30,1855-02-23,28422 days

### 데이터 프레임에서 행 삭제하기

In [458]:
scientists=scientists.set_index('Name') #Name 컴럼 값으로 데이터 프레임의 행 인덱스 설정

In [459]:
display(scientists.head())

,Born,Died,Age,Occupation,born_dt,died_dt,age_days
Name,,,,,,,
Rosaline Franklin,1920-07-25,1958-04-16,61,Chemist,1920-07-25,1958-04-16,13779 days
William Gosset,1876-06-13,1937-10-16,45,Statistician,1876-06-13,1937-10-16,22404 days
Florence Nightingale,1820-05-12,1910-08-13,37,Nurse,1820-05-12,1910-08-13,32964 days
Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days
Rachel Carson,1907-05-27,1964-04-14,90,Biologist,1907-05-27,1964-04-14,20777 days

In [460]:
scientists_without_franklin=scientists.drop(index=['Rosaline Franklin'])

In [461]:
scientists_without_franklin.head() #한 행이 삭제된 데이터프레임

,Born,Died,Age,Occupation,born_dt,died_dt,age_days
Name,,,,,,,
William Gosset,1876-06-13,1937-10-16,45,Statistician,1876-06-13,1937-10-16,22404 days
Florence Nightingale,1820-05-12,1910-08-13,37,Nurse,1820-05-12,1910-08-13,32964 days
Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days
Rachel Carson,1907-05-27,1964-04-14,90,Biologist,1907-05-27,1964-04-14,20777 days
John Snow,1813-03-15,1858-06-16,56,Physician,1813-03-15,1858-06-16,16529 days

In [462]:
scientists_without_multiple=scientists.drop(index=['Rosaline Franklin','William Gosset'])

In [463]:
display(scientists_without_multiple) #여러 행이 삭제된 데이터프레임

,Born,Died,Age,Occupation,born_dt,died_dt,age_days
Name,,,,,,,
Florence Nightingale,1820-05-12,1910-08-13,37,Nurse,1820-05-12,1910-08-13,32964 days
Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days
Rachel Carson,1907-05-27,1964-04-14,90,Biologist,1907-05-27,1964-04-14,20777 days
John Snow,1813-03-15,1858-06-16,56,Physician,1813-03-15,1858-06-16,16529 days
Alan Turing,1912-06-23,1954-06-07,66,Computer Scientist,1912-06-23,1954-06-07,15324 days
Johann Gauss,1777-04-30,1855-02-23,41,Mathematician,1777-04-30,1855-02-23,28422 days

In [464]:
display(scientists.head()) #원본은 유지하고 새로운 변수를 이용해 내용 삭제

,Born,Died,Age,Occupation,born_dt,died_dt,age_days
Name,,,,,,,
Rosaline Franklin,1920-07-25,1958-04-16,61,Chemist,1920-07-25,1958-04-16,13779 days
William Gosset,1876-06-13,1937-10-16,45,Statistician,1876-06-13,1937-10-16,22404 days
Florence Nightingale,1820-05-12,1910-08-13,37,Nurse,1820-05-12,1910-08-13,32964 days
Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days
Rachel Carson,1907-05-27,1964-04-14,90,Biologist,1907-05-27,1964-04-14,20777 days

In [465]:
scientists['age_years']=(scientists['age_days'].dt.days/365).apply(np.floor)
#.dt는 시리즈의 날짜/시간 관련 속성에 접근하게 해준다
#.days는 day정보만 정수로 추출한다
#.dt.day로 숫자로 변경
display(scientists.head())

,Born,Died,Age,Occupation,born_dt,died_dt,age_days,age_years
Name,,,,,,,,
Rosaline Franklin,1920-07-25,1958-04-16,61,Chemist,1920-07-25,1958-04-16,13779 days,37.0
William Gosset,1876-06-13,1937-10-16,45,Statistician,1876-06-13,1937-10-16,22404 days,61.0
Florence Nightingale,1820-05-12,1910-08-13,37,Nurse,1820-05-12,1910-08-13,32964 days,90.0
Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days,66.0
Rachel Carson,1907-05-27,1964-04-14,90,Biologist,1907-05-27,1964-04-14,20777 days,56.0

In [466]:
#assign()으로 열 수정하기
scientists=scientists.assign(
    age_days_assign=scientists['died_dt']-scientists['born_dt'],
    age_years_assign=(scientists['age_days'].dt.days/365).apply(np.floor)
)
display(scientists.head())
#apply() 이 시리즈의 각 값에 대해 특정 함수를 적용하고 싶을 때 사용
#assign() 기존 데이터프레임을 변경하지 않고 새로운 열이 추가되거나 변경된 새로운 데이터프레임을 반환
#괄호 안에는 새로 생성할 열의 이름과 그 값을 지정
#열이름 = 값

,Born,Died,Age,Occupation,born_dt,died_dt,age_days,age_years,age_days_assign,age_years_assign
Name,,,,,,,,,,
Rosaline Franklin,1920-07-25,1958-04-16,61,Chemist,1920-07-25,1958-04-16,13779 days,37.0,13779 days,37.0
William Gosset,1876-06-13,1937-10-16,45,Statistician,1876-06-13,1937-10-16,22404 days,61.0,22404 days,61.0
Florence Nightingale,1820-05-12,1910-08-13,37,Nurse,1820-05-12,1910-08-13,32964 days,90.0,32964 days,90.0
Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days,66.0,24345 days,66.0
Rachel Carson,1907-05-27,1964-04-14,90,Biologist,1907-05-27,1964-04-14,20777 days,56.0,20777 days,56.0

In [467]:
scientists=scientists.assign(
    age_days_assign=scientists['died_dt']-scientists['born_dt'],
    age_years_assign=lambda df_:(df_['age_days_assign'].dt.days/365).apply(np.floor)
)
display(scientists.head())
#df_라는 인자로 현재 assign()이 적용되고 있는 데이터프레임(즉, scientists 데이터프레임)을 참조할 수 있다.

,Born,Died,Age,Occupation,born_dt,died_dt,age_days,age_years,age_days_assign,age_years_assign
Name,,,,,,,,,,
Rosaline Franklin,1920-07-25,1958-04-16,61,Chemist,1920-07-25,1958-04-16,13779 days,37.0,13779 days,37.0
William Gosset,1876-06-13,1937-10-16,45,Statistician,1876-06-13,1937-10-16,22404 days,61.0,22404 days,61.0
Florence Nightingale,1820-05-12,1910-08-13,37,Nurse,1820-05-12,1910-08-13,32964 days,90.0,32964 days,90.0
Marie Curie,1867-11-07,1934-07-04,77,Chemist,1867-11-07,1934-07-04,24345 days,66.0,24345 days,66.0
Rachel Carson,1907-05-27,1964-04-14,90,Biologist,1907-05-27,1964-04-14,20777 days,56.0,20777 days,56.0

### 데이터프레임에서 열 삭제하기

In [468]:
print(scientists.columns)

Index(['Born', 'Died', 'Age', 'Occupation', 'born_dt', 'died_dt', 'age_days',
       'age_years', 'age_days_assign', 'age_years_assign'],
      dtype='object')

In [480]:
scientists_dropped=scientists.drop(['Age'],axis="columns") #axis=1과 같은 결과
print(scientists_dropped)
#원본 데이터프레임은 변경되지 않고, 원본을 변경하려면 inplace=True 인자를 추가해야 한다
#열 삭제 : axis="columns" 또는 axis=1, 삭제할 열의 이름을 리스트로 전달
#행 삭제 : axis="index" 또는 axis=0, scientists.drop([0],axis="index")는 0번 인덱스(첫번째 행)을 삭제

                            Born        Died          Occupation    born_dt  \
Name
Rosaline Franklin     1920-07-25  1958-04-16             Chemist 1920-07-25
William Gosset        1876-06-13  1937-10-16        Statistician 1876-06-13
Florence Nightingale  1820-05-12  1910-08-13               Nurse 1820-05-12
Marie Curie           1867-11-07  1934-07-04             Chemist 1867-11-07
Rachel Carson         1907-05-27  1964-04-14           Biologist 1907-05-27
John Snow             1813-03-15  1858-06-16           Physician 1813-03-15
Alan Turing           1912-06-23  1954-06-07  Computer Scientist 1912-06-23
Johann Gauss          1777-04-30  1855-02-23       Mathematician 1777-04-30

                        died_dt   age_days  age_years age_days_assign  \
Name
Rosaline Franklin    1958-04-16 13779 days       37.0      13779 days
William Gosset       1937-10-16 22404 days       61.0      22404 days
Florence Nightingale 1910-08-13 32964 days       90.0      32964 days
Marie Curie          1934-07-04 24345 days       66.0      24345 days
Rachel Carson        1964-04-14 20777 days       56.0      20777 days
John Snow            1858-06-16 16529 days       45.0      16529 days
Alan Turing          1954-06-07 15324 days       41.0      15324 days
Johann Gauss         1855-02-23 28422 days       77.0      28422 days

                      age_years_assign
Name
Rosaline Franklin                 37.0
William Gosset                    61.0
Florence Nightingale              90.0
Marie Curie                       66.0
Rachel Carson                     56.0
John Snow                         45.0
Alan Turing                       41.0
Johann Gauss                      77.0

In [485]:
print(scientists_dropped.columns)

Index(['Born', 'Died', 'Occupation', 'born_dt', 'died_dt', 'age_days',
       'age_years', 'age_days_assign', 'age_years_assign'],
      dtype='object')