<a href="https://colab.research.google.com/github/hjiwoong/bigdata/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B2%B0%ED%95%A9%EC%A0%95%EA%B7%9C%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
#구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

#드라이브에 저장된 폰트 등록
import matplotlib as mpl
import matplotlib.pyplot as plt #그래프 그리는 모듈
import matplotlib.font_manager as fm #폰트 관리하는 모듈

#드라이브 내 폰트 경로
font_path = "/content/drive/MyDrive/KWU/bigdata/dataPreProcessing/NanumGothic.ttf"

fm.fontManager.addfont(font_path)
mpl.rc('font',family = 'NanumGothic') #matplolib 기본 폰트로 설정
plt.rcParams['axes.unicode_minus'] = False #마이너스(-) 기호가 깨지지 않도록 유니코드 마이너스 비활성화

print("현재 폰트: ",plt.rcParams['font.family']) #현재 적용된 폰트 이름 출력

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
현재 폰트:  ['NanumGothic']

In [99]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#타이타닉 데이터 로드
titanic = pd.read_csv('/content/drive/MyDrive/KWU/bigdata/dataPreProcessing/train.csv')
print(titanic.shape)
titanic.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 실습용 데이터 생성

In [100]:
from pathlib import Path #파일 경로를 객체로 다루는 모듈
import os #운영체제 기능 모듈

#승객 기본 정보
passengers = titanic[['Survived', 'Sex', 'Age', 'Name']].copy()
passengers.insert(0,'passenger_id',range(1,len(titanic)+1))

#티켓 및 운임 정보
tickets = titanic[['Fare','Embarked','Pclass']].copy()
tickets.insert(0,'passenger_id',range(1,len(titanic)+1))
tickets.columns=['passenger_id','fare','embarked','pclass']

#객실 등급 상세 정보
class_info = pd.DataFrame({
    'pclass':[1,2,3],
    'class_name':['First Class','Second Class','Third Class'],
    'class_desc':['최상위 등급','중간 등급','일반 등급'],
    'base_fare':[50.0,20.0,8.0]
                           })

#출할지 정보
port_info = pd.DataFrame({
    'embarked':['S','C','Q'],
    'port_name':['Southhampton','Cherbourg','Queenstown'],
    'country':['영국','프랑스','아일랜드']
})

In [101]:
import os
#CSV 파일을 저장할 임시 디렉토리 생성
output_dir= '/content/drive/MyDrive/KWU/bigdata/eda/processed_data'
os.makedirs(output_dir, exist_ok=True)

#각 데이터 프레임을 CSV파일로 저장
passengers.to_csv(os.path.join(output_dir, 'passengers.csv'),index=False)
tickets.to_csv(os.path.join(output_dir, 'tickets.csv'),index=False)
class_info.to_csv(os.path.join(output_dir, 'class_info.csv'),index=False)
port_info.to_csv(os.path.join(output_dir, 'port_info.csv'),index=False)

In [102]:
#저장된 CSV 파일을 다시 불러오기
output_dir= '/content/drive/MyDrive/KWU/bigdata/eda/processed_data'

passenger = pd.read_csv(os.path.join(output_dir,'passengers.csv'))
tickets.to_csv(os.path.join(output_dir, 'tickets.csv'),index=False)
class_info.to_csv(os.path.join(output_dir, 'class_info.csv'),index=False)
port_info.to_csv(os.path.join(output_dir, 'port_info.csv'),index=False)

In [103]:
passenger

,passenger_id,Survived,Sex,Age,Name
0,1,0,male,22.0,"Braund, Mr. Owen Harris"
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,female,26.0,"Heikkinen, Miss. Laina"
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,male,35.0,"Allen, Mr. William Henry"
...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas"
887,888,1,female,19.0,"Graham, Miss. Margaret Edith"
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
889,890,1,male,26.0,"Behr, Mr. Karl Howell"
890,891,0,male,32.0,"Dooley, Mr. Patrick"

In [104]:
tickets

     passenger_id     fare embarked  pclass
0               1   7.2500        S       3
1               2  71.2833        C       1
2               3   7.9250        S       3
3               4  53.1000        S       1
4               5   8.0500        S       3
..            ...      ...      ...     ...
886           887  13.0000        S       2
887           888  30.0000        S       1
888           889  23.4500        S       3
889           890  30.0000        C       1
890           891   7.7500        Q       3

[891 rows x 4 columns]

In [105]:
class_info

   pclass    class_name class_desc  base_fare
0       1   First Class     최상위 등급       50.0
1       2  Second Class      중간 등급       20.0
2       3   Third Class      일반 등급        8.0

In [106]:
port_info

  embarked     port_name country
0        S  Southhampton      영국
1        C     Cherbourg     프랑스
2        Q    Queenstown    아일랜드

### concat() - 행 방향 연결(아래로 쌓기)

In [107]:
#데이터 생성: 1등석/2등석/3등석 승객을 각각 따로 분리
#'pclass':1등석 승객의 passenger_id를 tickets에서 필터링
p1 = passengers[passengers['passenger_id'].isin(tickets[tickets['pclass']==1]['passenger_id'])]
p1

,passenger_id,Survived,Sex,Age,Name
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
6,7,0,male,54.0,"McCarthy, Mr. Timothy J"
11,12,1,female,58.0,"Bonnell, Miss. Elizabeth"
23,24,1,male,28.0,"Sloper, Mr. William Thompson"
...,...,...,...,...,...
871,872,1,female,47.0,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)"
872,873,0,male,33.0,"Carlsson, Mr. Frans Olof"
879,880,1,female,56.0,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)"
887,888,1,female,19.0,"Graham, Miss. Margaret Edith"
889,890,1,male,26.0,"Behr, Mr. Karl Howell"

In [108]:
p2 = passengers[passengers['passenger_id'].isin(tickets[tickets['pclass']==2]['passenger_id'])]
p2

,passenger_id,Survived,Sex,Age,Name
9,10,1,female,14.0,"Nasser, Mrs. Nicholas (Adele Achem)"
15,16,1,female,55.0,"Hewlett, Mrs. (Mary D Kingcome)"
17,18,1,male,NaN,"Williams, Mr. Charles Eugene"
20,21,0,male,35.0,"Fynney, Mr. Joseph J"
21,22,1,male,34.0,"Beesley, Mr. Lawrence"
...,...,...,...,...,...
866,867,1,female,27.0,"Duran y More, Miss. Asuncion"
874,875,1,female,28.0,"Abelson, Mrs. Samuel (Hannah Wizosky)"
880,881,1,female,25.0,"Shelley, Mrs. William (Imanita Parrish Hall)"
883,884,0,male,28.0,"Banfield, Mr. Frederick James"
886,887,0,male,27.0,"Montvila, Rev. Juozas"

In [109]:
p3 = passengers[passengers['passenger_id'].isin(tickets[tickets['pclass']==3]['passenger_id'])]
p3

,passenger_id,Survived,Sex,Age,Name
0,1,0,male,22.0,"Braund, Mr. Owen Harris"
2,3,1,female,26.0,"Heikkinen, Miss. Laina"
4,5,0,male,35.0,"Allen, Mr. William Henry"
5,6,0,male,NaN,"Moran, Mr. James"
7,8,0,male,2.0,"Palsson, Master. Gosta Leonard"
...,...,...,...,...,...
882,883,0,female,22.0,"Dahlberg, Miss. Gerda Ulrika"
884,885,0,male,25.0,"Sutehall, Mr. Henry Jr"
885,886,0,female,39.0,"Rice, Mrs. William (Margaret Norton)"
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
890,891,0,male,32.0,"Dooley, Mr. Patrick"

In [110]:
#기본 concat: 여러 DataFrame을 행 방향으로 단순 연결
result_raw = pd.concat([p1,p2,p3])
print("기본 concat (인덱스 중복):")
print(result_raw.index.tolist())
result_raw

기본 concat (인덱스 중복):
[1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, 449, 452, 453, 456, 457, 460, 462, 467, 475, 484, 486, 487, 492, 493, 496, 498, 504, 505, 507, 512, 513, 515, 520, 523, 527, 536, 537, 539, 540, 544, 545, 550, 555, 556, 557, 558, 571, 572, 577, 581, 583, 585, 587, 591, 599, 602, 604, 607, 609, 621, 625, 627, 630, 632, 633, 641, 645, 647, 659, 660, 662, 669, 671, 679, 681, 689, 690, 694, 698, 700, 701, 707, 708, 710, 711, 712, 716, 724, 730, 737, 740, 741, 742, 745, 748, 759, 763, 765, 766, 779, 781, 782, 789, 793, 796, 802, 806, 809, 815, 820, 822, 829, 835, 839, 842, 849, 853, 856, 857, 862, 867, 871, 872, 879, 887, 889, 9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, 466, 472, 473, 476, 481, 506, 516, 518, 526, 529, 530, 535, 543, 546, 547, 549, 551, 562, 570, 576, 580, 582, 586, 594, 596, 600, 608, 615, 618, 619, 626, 635, 637, 651, 655, 658, 665, 666, 670, 672, 673, 674, 684, 685, 695, 705, 706, 714, 717, 720, 722, 723, 726, 728, 732, 733, 734, 747, 750, 754, 755, 757, 772, 774, 791, 795, 800, 801, 808, 812, 817, 827, 831, 841, 848, 854, 861, 864, 865, 866, 874, 880, 883, 886, 0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, 160, 162, 163, 164, 165, 167, 169, 171, 172, 173, 175, 176, 179, 180, 182, 184, 186, 188, 189, 192, 196, 197, 198, 200, 201, 202, 203, 204, 205, 206, 207, 208, 210, 212, 214, 216, 220, 222, 223, 225, 227, 229, 231, 233, 235, 240, 241, 243, 244, 246, 250, 251, 253, 254, 255, 260, 261, 264, 266, 267, 271, 274, 276, 278, 279, 280, 281, 282, 283, 285, 286, 287, 289, 293, 294, 296, 300, 301, 302, 304, 313, 315, 320, 321, 324, 326, 328, 330, 333, 335, 338, 347, 348, 349, 350, 352, 353, 354, 355, 358, 359, 360, 362, 363, 364, 365, 367, 368, 371, 372, 374, 376, 378, 379, 381, 382, 384, 386, 388, 391, 392, 394, 395, 396, 400, 401, 402, 403, 404, 406, 408, 409, 410, 411, 414, 415, 419, 420, 421, 422, 423, 424, 425, 428, 429, 431, 433, 436, 441, 442, 444, 448, 451, 454, 455, 459, 461, 464, 465, 468, 469, 470, 471, 474, 477, 478, 479, 480, 482, 483, 485, 488, 489, 490, 491, 494, 495, 497, 499, 500, 501, 502, 503, 508, 509, 510, 511, 514, 517, 519, 521, 522, 524, 525, 528, 531, 532, 533, 534, 538, 541, 542, 548, 552, 553, 554, 559, 560, 561, 563, 564, 565, 566, 567, 568, 569, 573, 574, 575, 578, 579, 584, 588, 589, 590, 592, 593, 595, 597, 598, 601, 603, 605, 606, 610, 611, 612, 613, 614, 616, 617, 620, 622, 623, 624, 628, 629, 631, 634, 636, 638, 639, 640, 642, 643, 644, 646, 648, 649, 650, 652, 653, 654, 656, 657, 661, 663, 664, 667, 668, 675, 676, 677, 678, 680, 682, 683, 686, 687, 688, 691, 692, 693, 696, 697, 699, 702, 703, 704, 709, 713, 715, 718, 719, 721, 725, 727, 729, 731, 735, 736, 738, 739, 743, 744, 746, 749, 751, 752, 753, 756, 758, 760, 761, 762, 764, 767, 768, 769, 770, 771, 773, 775, 776, 777, 778, 780, 783, 784, 785, 786, 787, 788, 790, 792, 794, 797, 798, 799, 803, 804, 805, 807, 810, 811, 813, 814, 816, 818, 819, 821, 823, 824, 825, 826, 828, 830, 832, 833, 834, 836, 837, 838, 840, 843, 844, 845, 846, 847, 850, 851, 852, 855, 858, 859, 860, 863, 868, 869, 870, 873, 875, 876, 877, 878, 881, 882, 884, 885, 888, 890]

,passenger_id,Survived,Sex,Age,Name
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
6,7,0,male,54.0,"McCarthy, Mr. Timothy J"
11,12,1,female,58.0,"Bonnell, Miss. Elizabeth"
23,24,1,male,28.0,"Sloper, Mr. William Thompson"
...,...,...,...,...,...
882,883,0,female,22.0,"Dahlberg, Miss. Gerda Ulrika"
884,885,0,male,25.0,"Sutehall, Mr. Henry Jr"
885,886,0,female,39.0,"Rice, Mrs. William (Margaret Norton)"
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
890,891,0,male,32.0,"Dooley, Mr. Patrick"

In [111]:
#연결 수 인덱스를 0부터 새로 부여
result_reset = pd.concat([p1,p2,p3],ignore_index=True)
print('ignore_index=True (인덱스 재설정):')
print(result_reset.index.tolist())
result_reset

ignore_index=True (인덱스 재설정):
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890]

,passenger_id,Survived,Sex,Age,Name
0,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
1,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
2,7,0,male,54.0,"McCarthy, Mr. Timothy J"
3,12,1,female,58.0,"Bonnell, Miss. Elizabeth"
4,24,1,male,28.0,"Sloper, Mr. William Thompson"
...,...,...,...,...,...
886,883,0,female,22.0,"Dahlberg, Miss. Gerda Ulrika"
887,885,0,male,25.0,"Sutehall, Mr. Henry Jr"
888,886,0,female,39.0,"Rice, Mrs. William (Margaret Norton)"
889,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
890,891,0,male,32.0,"Dooley, Mr. Patrick"

### concat() - join 옵션(열 이름이 다를 때)

In [112]:
#데이터 생성
df_a = pd.DataFrame({
    'passenger':[1,2,3],
    'name':['Alice','Bob','Carol'],
    'age':[29,35,24]
})
df_a

   passenger   name  age
0          1  Alice   29
1          2    Bob   35
2          3  Carol   24

In [113]:
df_b = pd.DataFrame({
    'passenger':[4,5,6],
    'name':['Dave','Eve','Frank'],
    'ticket_no':['A123','B456','C789']
})
df_b

   passenger   name ticket_no
0          4   Dave      A123
1          5    Eve      B456
2          6  Frank      C789

In [114]:
#열 이름이 일부 다른 두 DataFrame을 concat할 때 열 불일치 처리 방법
#outer join (기본 값 join='outer')
result_outer = pd.concat([df_a,df_b],ignore_index=True)
print('outer join(기본):')
print(result_outer)

#inner join: 양쪽에 공통으로 있는 열만 유지
result_inner = pd.concat([df_a,df_b],join='inner',ignore_index=True)
print("inner join(공통 열만):")
print(result_inner)

outer join(기본):
   passenger   name   age ticket_no
0          1  Alice  29.0       NaN
1          2    Bob  35.0       NaN
2          3  Carol  24.0       NaN
3          4   Dave   NaN      A123
4          5    Eve   NaN      B456
5          6  Frank   NaN      C789
inner join(공통 열만):
   passenger   name
0          1  Alice
1          2    Bob
2          3  Carol
3          4   Dave
4          5    Eve
5          6  Frank

### concat() - 열 방향 연결(옆으로 붙이기)

In [115]:
#데이터 생성
base_info = passengers[['passenger_id','Name','Age']].head(5).reset_index(drop=True) #기존 인덱스를 열로 추가하지 않고
print(base_info)

extra_info = pd.DataFrame({
    'survived': titanic['Survived'].head(5).values,
    'sex': titanic['Sex'].head(5).values,
})
print(extra_info)

   passenger_id                                               Name   Age
0             1                            Braund, Mr. Owen Harris  22.0
1             2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2             3                             Heikkinen, Miss. Laina  26.0
3             4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4             5                           Allen, Mr. William Henry  35.0
   survived     sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

In [116]:
#axis=1 열 방향 연결
combined = pd.concat([base_info,extra_info],axis=1)
print('열방향 연결 결과:')
display(combined)

열방향 연결 결과:

,passenger_id,Name,Age,survived,sex
0,1,"Braund, Mr. Owen Harris",22.0,0,male
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,female
2,3,"Heikkinen, Miss. Laina",26.0,1,female
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,female
4,5,"Allen, Mr. William Henry",35.0,0,male

In [117]:
#인덱스가 다를 때 열 방향 concat 주의
df_x=pd.DataFrame({'A':[1,2,3]},index=[0,1,2])
df_y=pd.DataFrame({'B':[10,20,30]},index=[1,2,3])

result_diff_idx = pd.concat([df_x,df_y], axis=1)
print("인덱스가 다를 때 열 방향 concat:")
display(result_diff_idx) #인덱스 기준으로 매칭

인덱스가 다를 때 열 방향 concat:

     A     B
0  1.0   NaN
1  2.0  10.0
2  3.0  20.0
3  NaN  30.0

### merge() - inner join(일대일)

In [118]:
passenger

,passenger_id,Survived,Sex,Age,Name
0,1,0,male,22.0,"Braund, Mr. Owen Harris"
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,female,26.0,"Heikkinen, Miss. Laina"
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,male,35.0,"Allen, Mr. William Henry"
...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas"
887,888,1,female,19.0,"Graham, Miss. Margaret Edith"
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
889,890,1,male,26.0,"Behr, Mr. Karl Howell"
890,891,0,male,32.0,"Dooley, Mr. Patrick"

In [119]:
tickets

     passenger_id     fare embarked  pclass
0               1   7.2500        S       3
1               2  71.2833        C       1
2               3   7.9250        S       3
3               4  53.1000        S       1
4               5   8.0500        S       3
..            ...      ...      ...     ...
886           887  13.0000        S       2
887           888  30.0000        S       1
888           889  23.4500        S       3
889           890  30.0000        C       1
890           891   7.7500        Q       3

[891 rows x 4 columns]

In [120]:
merged_inner = passengers.merge(tickets, on='passenger_id', how='inner') #on: 양쪽에 공통으로 있는 열을 기준으로 병합, inner:양쪽 모두에 키가 있는 행만
print('inner merge 결과:')
display(merged_inner)

inner merge 결과:

,passenger_id,Survived,Sex,Age,Name,fare,embarked,pclass
0,1,0,male,22.0,"Braund, Mr. Owen Harris",7.2500,S,3
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,1
2,3,1,female,26.0,"Heikkinen, Miss. Laina",7.9250,S,3
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,S,1
4,5,0,male,35.0,"Allen, Mr. William Henry",8.0500,S,3
...,...,...,...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas",13.0000,S,2
887,888,1,female,19.0,"Graham, Miss. Margaret Edith",30.0000,S,1
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,S,3
889,890,1,male,26.0,"Behr, Mr. Karl Howell",30.0000,C,1
890,891,0,male,32.0,"Dooley, Mr. Patrick",7.7500,Q,3

### merge() - left/right/outer join 비교

In [121]:
#일부 승객은 티켓 정보가 없는 상황으로 비교
passengers_full = passengers.merge(tickets, on='passenger_id', how='left')
print('left join 결과:')
display(passengers_full)

left join 결과:

,passenger_id,Survived,Sex,Age,Name,fare,embarked,pclass
0,1,0,male,22.0,"Braund, Mr. Owen Harris",7.2500,S,3
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,1
2,3,1,female,26.0,"Heikkinen, Miss. Laina",7.9250,S,3
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,S,1
4,5,0,male,35.0,"Allen, Mr. William Henry",8.0500,S,3
...,...,...,...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas",13.0000,S,2
887,888,1,female,19.0,"Graham, Miss. Margaret Edith",30.0000,S,1
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,S,3
889,890,1,male,26.0,"Behr, Mr. Karl Howell",30.0000,C,1
890,891,0,male,32.0,"Dooley, Mr. Patrick",7.7500,Q,3

In [122]:
tickets_partial = tickets[tickets['passenger_id']<=800].copy()
tickets_partial

     passenger_id     fare embarked  pclass
0               1   7.2500        S       3
1               2  71.2833        C       1
2               3   7.9250        S       3
3               4  53.1000        S       1
4               5   8.0500        S       3
..            ...      ...      ...     ...
795           796  13.0000        S       2
796           797  25.9292        S       1
797           798   8.6833        S       3
798           799   7.2292        C       3
799           800  24.1500        S       3

[800 rows x 4 columns]

In [162]:
#left join:왼쪽(passengers) 전체 유지, 오른쪽(tickets)에 없으면 NaN
left_result = passengers_full.merge(tickets_partial, on='passenger_id',how='left', suffixes=('_x', '_y')) # 중복 컬럼을 명확히 하기 위해 suffixes 명시
print(f"left join:{len(left_result)}행 (승객 전체 유지)")
print(f"fare_y NaN 수:{left_result['fare_y'].isnull().sum()}") # 'fare' 대신 'fare_y' 사용
display(left_result)

#right join: 오른쪽(tickets) 전체 유지, 왼쪽(passengers)에 없으면 NaN
right_result = passengers_full.merge(tickets_partial, on='passenger_id', how='right', suffixes=('_x', '_y'))
print(f"right join:{len(right_result)}행 (티켓 전체 유지)")
display(right_result)

#outer join: 양쪽 전체 유지, 없는 쪽은 NaN
outer_result = passengers_full.merge(tickets_partial, on='passenger_id', how='outer', suffixes=('_x', '_y'))
print(f"outer join:{len(outer_result)}행 (전체 유지)")
display(outer_result)

left join:891행 (승객 전체 유지)
fare_y NaN 수:91

,passenger_id,Survived,Sex,Age,Name,fare_x,embarked_x,pclass_x,fare_y,embarked_y,pclass_y
0,1,0,male,22.0,"Braund, Mr. Owen Harris",7.2500,S,3,7.2500,S,3.0
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,1,71.2833,C,1.0
2,3,1,female,26.0,"Heikkinen, Miss. Laina",7.9250,S,3,7.9250,S,3.0
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,S,1,53.1000,S,1.0
4,5,0,male,35.0,"Allen, Mr. William Henry",8.0500,S,3,8.0500,S,3.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas",13.0000,S,2,NaN,NaN,NaN
887,888,1,female,19.0,"Graham, Miss. Margaret Edith",30.0000,S,1,NaN,NaN,NaN
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,S,3,NaN,NaN,NaN
889,890,1,male,26.0,"Behr, Mr. Karl Howell",30.0000,C,1,NaN,NaN,NaN
890,891,0,male,32.0,"Dooley, Mr. Patrick",7.7500,Q,3,NaN,NaN,NaN

right join:800행 (티켓 전체 유지)

,passenger_id,Survived,Sex,Age,Name,fare_x,embarked_x,pclass_x,fare_y,embarked_y,pclass_y
0,1,0,male,22.0,"Braund, Mr. Owen Harris",7.2500,S,3,7.2500,S,3
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,1,71.2833,C,1
2,3,1,female,26.0,"Heikkinen, Miss. Laina",7.9250,S,3,7.9250,S,3
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,S,1,53.1000,S,1
4,5,0,male,35.0,"Allen, Mr. William Henry",8.0500,S,3,8.0500,S,3
...,...,...,...,...,...,...,...,...,...,...,...
795,796,0,male,39.0,"Otter, Mr. Richard",13.0000,S,2,13.0000,S,2
796,797,1,female,49.0,"Leader, Dr. Alice (Farnham)",25.9292,S,1,25.9292,S,1
797,798,1,female,31.0,"Osman, Mrs. Mara",8.6833,S,3,8.6833,S,3
798,799,0,male,30.0,"Ibrahim Shawah, Mr. Yousseff",7.2292,C,3,7.2292,C,3
799,800,0,female,30.0,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",24.1500,S,3,24.1500,S,3

outer join:891행 (전체 유지)

,passenger_id,Survived,Sex,Age,Name,fare_x,embarked_x,pclass_x,fare_y,embarked_y,pclass_y
0,1,0,male,22.0,"Braund, Mr. Owen Harris",7.2500,S,3,7.2500,S,3.0
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,1,71.2833,C,1.0
2,3,1,female,26.0,"Heikkinen, Miss. Laina",7.9250,S,3,7.9250,S,3.0
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,S,1,53.1000,S,1.0
4,5,0,male,35.0,"Allen, Mr. William Henry",8.0500,S,3,8.0500,S,3.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas",13.0000,S,2,NaN,NaN,NaN
887,888,1,female,19.0,"Graham, Miss. Margaret Edith",30.0000,S,1,NaN,NaN,NaN
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,S,3,NaN,NaN,NaN
889,890,1,male,26.0,"Behr, Mr. Karl Howell",30.0000,C,1,NaN,NaN,NaN
890,891,0,male,32.0,"Dooley, Mr. Patrick",7.7500,Q,3,NaN,NaN,NaN

### merge() - 열 이름이 다를 때 (left_on/right_on)

In [124]:
#데이터 생성
passengers_renamed = passengers.rename(columns={'passenger_id':'p_id'})
passengers_renamed

,p_id,Survived,Sex,Age,Name
0,1,0,male,22.0,"Braund, Mr. Owen Harris"
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,female,26.0,"Heikkinen, Miss. Laina"
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,male,35.0,"Allen, Mr. William Henry"
...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas"
887,888,1,female,19.0,"Graham, Miss. Margaret Edith"
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
889,890,1,male,26.0,"Behr, Mr. Karl Howell"
890,891,0,male,32.0,"Dooley, Mr. Patrick"

In [125]:
tickets

     passenger_id     fare embarked  pclass
0               1   7.2500        S       3
1               2  71.2833        C       1
2               3   7.9250        S       3
3               4  53.1000        S       1
4               5   8.0500        S       3
..            ...      ...      ...     ...
886           887  13.0000        S       2
887           888  30.0000        S       1
888           889  23.4500        S       3
889           890  30.0000        C       1
890           891   7.7500        Q       3

[891 rows x 4 columns]

In [126]:
merged_diff = passengers_renamed.merge(tickets, left_on='p_id', right_on='passenger_id', how='inner')
print('열 이름이 다를 때 merge 결과:')
display(merged_diff[['p_id','passenger_id','Name','fare']].head(3))
#how='inner':양쪽 모두에 키가 있는 행만 유지

merged_diff = merged_diff.drop(columns=['passenger_id'])
print('중복 키 열 제거 후:')
display(merged_diff.head(3))

열 이름이 다를 때 merge 결과:

,p_id,passenger_id,Name,fare
0,1,1,"Braund, Mr. Owen Harris",7.2500
1,2,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833
2,3,3,"Heikkinen, Miss. Laina",7.9250

중복 키 열 제거 후:

,p_id,Survived,Sex,Age,Name,fare,embarked,pclass
0,1,0,male,22.0,"Braund, Mr. Owen Harris",7.2500,S,3
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,1
2,3,1,female,26.0,"Heikkinen, Miss. Laina",7.9250,S,3

### merge() - 다단계 병합 (3개 테이블 연결)

In [127]:
passenger

,passenger_id,Survived,Sex,Age,Name
0,1,0,male,22.0,"Braund, Mr. Owen Harris"
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,female,26.0,"Heikkinen, Miss. Laina"
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,male,35.0,"Allen, Mr. William Henry"
...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas"
887,888,1,female,19.0,"Graham, Miss. Margaret Edith"
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
889,890,1,male,26.0,"Behr, Mr. Karl Howell"
890,891,0,male,32.0,"Dooley, Mr. Patrick"

In [128]:
tickets

     passenger_id     fare embarked  pclass
0               1   7.2500        S       3
1               2  71.2833        C       1
2               3   7.9250        S       3
3               4  53.1000        S       1
4               5   8.0500        S       3
..            ...      ...      ...     ...
886           887  13.0000        S       2
887           888  30.0000        S       1
888           889  23.4500        S       3
889           890  30.0000        C       1
890           891   7.7500        Q       3

[891 rows x 4 columns]

In [129]:
class_info

   pclass    class_name class_desc  base_fare
0       1   First Class     최상위 등급       50.0
1       2  Second Class      중간 등급       20.0
2       3   Third Class      일반 등급        8.0

In [130]:
port_info

  embarked     port_name country
0        S  Southhampton      영국
1        C     Cherbourg     프랑스
2        Q    Queenstown    아일랜드

In [131]:
#STEP 1: 승객 기본 정보 + 티켓 정보 병합
step1 = passengers.merge(tickets, on='passenger_id', how='left')
step1

#STEP 2: +객실 등급 상세 정보 병합
step2 = step1.merge(class_info, on='pclass', how='left')
step2

#STEP 3: +출항지 정보 병합
step3 = step2.merge(port_info, on='embarked', how='left')
display(step3)
print('최종 통합 테이블 컬럼')
print(step3.columns.tolist())

print('\n샘플 데이터 (상위 3행):')
show_cols = ['passenger_id', 'Survived', 'Sex', 'Age', 'Name', 'fare', 'pclass', 'class_name', 'port_name', 'country']
print(step3[show_cols].head(3).to_string()) #생략 없이 전체 내용 표시

,passenger_id,Survived,Sex,Age,Name,fare,embarked,pclass,class_name,class_desc,base_fare,port_name,country
0,1,0,male,22.0,"Braund, Mr. Owen Harris",7.2500,S,3,Third Class,일반 등급,8.0,Southhampton,영국
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,1,First Class,최상위 등급,50.0,Cherbourg,프랑스
2,3,1,female,26.0,"Heikkinen, Miss. Laina",7.9250,S,3,Third Class,일반 등급,8.0,Southhampton,영국
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,S,1,First Class,최상위 등급,50.0,Southhampton,영국
4,5,0,male,35.0,"Allen, Mr. William Henry",8.0500,S,3,Third Class,일반 등급,8.0,Southhampton,영국
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas",13.0000,S,2,Second Class,중간 등급,20.0,Southhampton,영국
887,888,1,female,19.0,"Graham, Miss. Margaret Edith",30.0000,S,1,First Class,최상위 등급,50.0,Southhampton,영국
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,S,3,Third Class,일반 등급,8.0,Southhampton,영국
889,890,1,male,26.0,"Behr, Mr. Karl Howell",30.0000,C,1,First Class,최상위 등급,50.0,Cherbourg,프랑스
890,891,0,male,32.0,"Dooley, Mr. Patrick",7.7500,Q,3,Third Class,일반 등급,8.0,Queenstown,아일랜드

최종 통합 테이블 컬럼
['passenger_id', 'Survived', 'Sex', 'Age', 'Name', 'fare', 'embarked', 'pclass', 'class_name', 'class_desc', 'base_fare', 'port_name', 'country']

샘플 데이터 (상위 3행):
   passenger_id  Survived     Sex   Age                                                 Name     fare  pclass   class_name     port_name country
0             1         0    male  22.0                              Braund, Mr. Owen Harris   7.2500       3  Third Class  Southhampton      영국
1             2         1  female  38.0  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  71.2833       1  First Class     Cherbourg     프랑스
2             3         1  female  26.0                               Heikkinen, Miss. Laina   7.9250       3  Third Class  Southhampton      영국

### 여러 파일 자동통합 (분산 파일 처리)

In [132]:
#월별로 분리된 타이타닉 승객 데이터 파일 통합
#실습용 파일 생성 후 통합

os.makedirs('/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly', exist_ok=True)

#실습용 월별 파일 생성(승객 891명을 3개월치로 분할)
splits=np.array_split(passengers,3) #행을 3개로 균등하게 분할
months = ['1912_01','1912_02','1912_03']

for month, chunk in zip(months, splits):
  path=f'/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly/passengers_{month}.csv'
  chunk.to_csv(path, index=False)
  print(f"생성:{path} ({len(chunk)}행)")

생성:/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly/passengers_1912_01.csv (297행)
생성:/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly/passengers_1912_02.csv (297행)
생성:/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly/passengers_1912_03.csv (297행)

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [133]:
#파일 읽기
file_list = list(Path('/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly').glob('passengers_*.csv')) #패턴과 일치하는 파일 목록 반환
file_list.sort()
file_list

[PosixPath('/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly/passengers_1912_01.csv'),
 PosixPath('/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly/passengers_1912_02.csv'),
 PosixPath('/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly/passengers_1912_03.csv')]

In [134]:
df_list = [] #각 파일에서 읽은 DataFrame을 담을 빈 리스트
for f in file_list:
  df=pd.read_csv(f)
  df['source_file']=f.name
  df_list.append(df)

df_list

[     passenger_id  Survived     Sex   Age  \
 0               1         0    male  22.0
 1               2         1  female  38.0
 2               3         1  female  26.0
 3               4         1  female  35.0
 4               5         0    male  35.0
 ..            ...       ...     ...   ...
 292           293         0    male  36.0
 293           294         0  female  24.0
 294           295         0    male  24.0
 295           296         0    male   NaN
 296           297         0    male  23.5

                                                   Name             source_file
 0                              Braund, Mr. Owen Harris  passengers_1912_01.csv
 1    Cumings, Mrs. John Bradley (Florence Briggs Th...  passengers_1912_01.csv
 2                               Heikkinen, Miss. Laina  passengers_1912_01.csv
 3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  passengers_1912_01.csv
 4                             Allen, Mr. William Henry  passengers_1912_01.csv
 ..                                                 ...                     ...
 292                             Levy, Mr. Rene Jacques  passengers_1912_01.csv
 293                                Haas, Miss. Aloisia  passengers_1912_01.csv
 294                                   Mineff, Mr. Ivan  passengers_1912_01.csv
 295                                  Lewy, Mr. Ervin G  passengers_1912_01.csv
 296                                 Hanna, Mr. Mansour  passengers_1912_01.csv

 [297 rows x 6 columns],
      passenger_id  Survived     Sex   Age  \
 0             298         0  female   2.0
 1             299         1    male   NaN
 2             300         1  female  50.0
 3             301         1  female   NaN
 4             302         1    male   NaN
 ..            ...       ...     ...   ...
 292           590         0    male   NaN
 293           591         0    male  35.0
 294           592         1  female  52.0
 295           593         0    male  47.0
 296           594         0  female   NaN

                                                 Name             source_file
 0                       Allison, Miss. Helen Loraine  passengers_1912_02.csv
 1                              Saalfeld, Mr. Adolphe  passengers_1912_02.csv
 2    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  passengers_1912_02.csv
 3           Kelly, Miss. Anna Katherine "Annie Kate"  passengers_1912_02.csv
 4                                 McCoy, Mr. Bernard  passengers_1912_02.csv
 ..                                               ...                     ...
 292                              Murdlin, Mr. Joseph  passengers_1912_02.csv
 293                             Rintamaki, Mr. Matti  passengers_1912_02.csv
 294  Stephenson, Mrs. Walter Bertram (Martha Eustis)  passengers_1912_02.csv
 295                       Elsbury, Mr. William James  passengers_1912_02.csv
 296                               Bourke, Miss. Mary  passengers_1912_02.csv

 [297 rows x 6 columns],
      passenger_id  Survived     Sex   Age  \
 0             595         0    male  37.0
 1             596         0    male  36.0
 2             597         1  female   NaN
 3             598         0    male  49.0
 4             599         0    male   NaN
 ..            ...       ...     ...   ...
 292           887         0    male  27.0
 293           888         1  female  19.0
 294           889         0  female   NaN
 295           890         1    male  26.0
 296           891         0    male  32.0

                                          Name             source_file
 0                     Chapman, Mr. John Henry  passengers_1912_03.csv
 1                 Van Impe, Mr. Jean Baptiste  passengers_1912_03.csv
 2                  Leitch, Miss. Jessie Wills  passengers_1912_03.csv
 3                         Johnson, Mr. Alfred  passengers_1912_03.csv
 4                           Boulos, Mr. Hanna  passengers_1912_03.csv
 ..                                        ...                     ...
 292                     Montvila, Rev. Juozas  passengers_1912_03.csv
 293              Graham, Miss. Margaret Edith  passengers_1912_03.csv
 294  Johnston, Miss. Catherine Helen "Carrie"  passengers_1912_03.csv
 295                     Behr, Mr. Karl Howell  passengers_1912_03.csv
 296                       Dooley, Mr. Patrick  passengers_1912_03.csv

 [297 rows x 6 columns]]

In [135]:
result_loop = pd.concat(df_list, ignore_index=True)
result_loop

,passenger_id,Survived,Sex,Age,Name,source_file
0,1,0,male,22.0,"Braund, Mr. Owen Harris",passengers_1912_01.csv
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",passengers_1912_01.csv
2,3,1,female,26.0,"Heikkinen, Miss. Laina",passengers_1912_01.csv
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",passengers_1912_01.csv
4,5,0,male,35.0,"Allen, Mr. William Henry",passengers_1912_01.csv
...,...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas",passengers_1912_03.csv
887,888,1,female,19.0,"Graham, Miss. Margaret Edith",passengers_1912_03.csv
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie""",passengers_1912_03.csv
889,890,1,male,26.0,"Behr, Mr. Karl Howell",passengers_1912_03.csv
890,891,0,male,32.0,"Dooley, Mr. Patrick",passengers_1912_03.csv

In [136]:
#리스트 컴프리헨션 방식 (간결)
output_dir_monthly='/content/drive/MyDrive/KWU/bigdata/eda/titanic_monthly'
result_comp = pd.concat([
    pd.read_csv(f) for f in sorted(Path(output_dir_monthly).glob('*.csv'))
], ignore_index=True)

print(f'컴프리헨션 방식:{result_comp.shape}')

컴프리헨션 방식:(891, 5)

In [141]:
#검증 : 분할 파일 합계와 통합 결과 행 수가 같은지 검증
total_rows=sum(len(pd.read_csv(f)) for f in file_list)

#try-except로 오류를 잡아서 프로그램 중단 없이 오류 메시지만 출력
try:
  assert len(result_comp)==total_rows, '행 수 불일치' #assert 조건이 False 일 때, 뒤는 AssertionError와 함께 출력될 메시지
except AssertionError as e:
  print(f"AssertionError:{e}")

print(f'검증 통과: 분할 파일 합계({total_rows})==통합 결과({len(result_comp)})')

검증 통과: 분할 파일 합계(891)==통합 결과(891)

### 데이터 정규화 - 중복 제거 및 테이블 분리

In [151]:
#정규화 전: 중복이 많은 단일 테이블(같은 등급 승객마다 등급 정보가 반복)
wide_table = passengers.merge(tickets, on='passenger_id').merge(class_info, on='pclass')
print(f"정규화 전 테이블:{wide_table.shape}")
print(f"'class_name' 중복 수:{wide_table['class_name'].duplicated().sum()}") #중복 개수 집계

정규화 전 테이블:(891, 11)
'class_name' 중복 수:888

In [153]:
wide_table

,passenger_id,Survived,Sex,Age,Name,fare,embarked,pclass,class_name,class_desc,base_fare
0,1,0,male,22.0,"Braund, Mr. Owen Harris",7.2500,S,3,Third Class,일반 등급,8.0
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,1,First Class,최상위 등급,50.0
2,3,1,female,26.0,"Heikkinen, Miss. Laina",7.9250,S,3,Third Class,일반 등급,8.0
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,S,1,First Class,최상위 등급,50.0
4,5,0,male,35.0,"Allen, Mr. William Henry",8.0500,S,3,Third Class,일반 등급,8.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,male,27.0,"Montvila, Rev. Juozas",13.0000,S,2,Second Class,중간 등급,20.0
887,888,1,female,19.0,"Graham, Miss. Margaret Edith",30.0000,S,1,First Class,최상위 등급,50.0
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,S,3,Third Class,일반 등급,8.0
889,890,1,male,26.0,"Behr, Mr. Karl Howell",30.0000,C,1,First Class,최상위 등급,50.0
890,891,0,male,32.0,"Dooley, Mr. Patrick",7.7500,Q,3,Third Class,일반 등급,8.0

In [159]:
#등급 정보 테이블 분리
class_table = wide_table[['pclass','class_name','class_desc','base_fare']].drop_duplicates().reset_index(drop=True)
print(f"[분리] 등급 정보 테이블:{class_table.shape}") #중복 행 제거
print(class_table)

#메인 테이블에서 분리된 열 제거
main_table = wide_table.drop(columns=['class_name','class_desc','base_fare'])
print(f"[정리] 메인 테이블:{main_table.shape}")
print(main_table.head(3))

#필요할 때 merge로 복원
restored = main_table.merge(class_table, on='pclass', how='left')
print(f"[복원] 병합 후:{restored.shape}")
print(restored.head(3))

#원본과 동일한지 검증
assert set(restored.columns) == set(wide_table.columns), '열 불일치'
assert len(restored) == len(wide_table), '행 수 불일치'
print('정규화 후 복원 검증 통과')

#정규화 효과 비교
before_size = wide_table[['pclass','class_name','class_desc','base_fare']].memory_usage(deep=True).sum()
after_size = class_table.memory_usage(deep=True).sum() #deep=True: 문자열 실제 메모리 포함
print(f"정규화 전 등급 정보 메모리:{before_size:,}bytes")
print(f"정규롸 후 등급 정보 메모리:{after_size:,}bytes")
print(f"절감율:{(1-after_size/before_size)*100:.1f}%")

[분리] 등급 정보 테이블:(3, 4)
   pclass    class_name class_desc  base_fare
0       3   Third Class      일반 등급        8.0
1       1   First Class     최상위 등급       50.0
2       2  Second Class      중간 등급       20.0
[정리] 메인 테이블:(891, 8)
   passenger_id  Survived     Sex   Age  \
0             1         0    male  22.0
1             2         1  female  38.0
2             3         1  female  26.0

                                                Name     fare embarked  pclass
0                            Braund, Mr. Owen Harris   7.2500        S       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833        C       1
2                             Heikkinen, Miss. Laina   7.9250        S       3
[복원] 병합 후:(891, 11)
   passenger_id  Survived     Sex   Age  \
0             1         0    male  22.0
1             2         1  female  38.0
2             3         1  female  26.0

                                                Name     fare embarked  \
0                            Braund, Mr. Owen Harris   7.2500        S
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833        C
2                             Heikkinen, Miss. Laina   7.9250        S

   pclass   class_name class_desc  base_fare
0       3  Third Class      일반 등급        8.0
1       1  First Class     최상위 등급       50.0
2       3  Third Class      일반 등급        8.0
정규화 후 복원 검증 통과
정규화 전 등급 정보 메모리:149,302bytes
정규롸 후 등급 정보 메모리:636bytes
절감율:99.6%

### 종합 - 타이타닉 전체 전처리 파이프라인 최종 완성

In [163]:
titanic_final = pd.read_csv('/content/drive/MyDrive/KWU/bigdata/dataPreProcessing/train.csv')
titanic_final = titanic_final.drop(columns=['Cabin'])

#데이터 결합
titanic_final = titanic_final.merge(port_info, left_on='Embarked',right_on='embarked',how='left')

# 결측치 처리
titanic_final['Age'] = titanic_final.groupby(['Sex','Pclass'])['Age'].transform(lambda x:x.fillna(x.median()))
titanic_final['Embarked'] = titanic_final['Embarked'].fillna(titanic_final['Embarked'].mode()[0])
titanic_final['port_name'] = titanic_final['port_name'].fillna('Southampton')
titanic_final['country'] = titanic_final['country'].fillna('영국')

# 이상치 처리 - 캡핑
Q1, Q3 = titanic_final['Fare'].quantile([0.25,0.75])
titanic_final['Fare'] = titanic_final['Fare'].clip(upper=Q3 + 1.5 * (Q3 - Q1)) #초과 값을 상한으로 대체

# 분포 변환 - 로그 변환
titanic_final['Fare'] = np.log1p(titanic_final['Fare']) #양의 왜도

# 파생 변수 생성
titanic_final['FamilySize'] = titanic_final['SibSp'] + titanic_final['Parch'] + 1
titanic_final['IsAlone'] = (titanic_final['FamilySize'] == 1).astype(int)
titanic_final['Title'] = titanic_final['Name'].str.extract(r',\s*([^\,]+)\.').squeeze()
titanic_final['Title'] = titanic_final['Title'].apply(lambda x:x if x in ['Mr','Miss','Mrs','Master'] else 'Other')

# 범주형 인코딩
# 명목형 변수(순서 없음) -> 원-핫 인코딩
titanic_final = pd.get_dummies(titanic_final, columns=['Sex','Embarked','Title'],drop_first=True)

# 순서형 변수(순서 있음) -> 순서형 인코딩
titanic_final['Pclass'] = titanic_final['Pclass'].map({1:2,2:1,3:0})

# 불필요 열 제거
titanic_final = titanic_final.drop(columns=['Name','Ticket','SibSp','Parch','port_name','country','embarked'])

# 스케일링
from sklearn.preprocessing import StandardScaler #평균=0, 표준편차=1로 표준화
num_cols = ['Age','Fare','FamilySize']
scaler = StandardScaler()
titanic_final[num_cols] = scaler.fit_transform(titanic_final[num_cols])

# 최종 결과 확인
print(f"\n최종 shape:{titanic_final.shape}")
print(f"결측치:{titanic_final.isnull().sum().sum()}개")
print(f"\n최종 컬럼 목록:")
print(titanic_final.columns.tolist())
print(f"\n데이터 미리보기:")
print(titanic_final.head(3).round(3))

최종 shape:(891, 14)
결측치:0개

최종 컬럼 목록:
['PassengerId', 'Survived', 'Pclass', 'Age', 'Fare', 'FamilySize', 'IsAlone', 'Sex_male', 'Embarked_Q', 'Embarked_S', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Other']

데이터 미리보기:
   PassengerId  Survived  Pclass    Age   Fare  FamilySize  IsAlone  Sex_male  \
0            1         0       0 -0.535 -0.938       0.059        0      True
1            2         1       2  0.668  1.563       0.059        0     False
2            3         1       0 -0.234 -0.844      -0.561        1     False

   Embarked_Q  Embarked_S  Title_Miss  Title_Mr  Title_Mrs  Title_Other
0       False        True       False      True      False        False
1       False       False       False     False       True        False
2       False        True        True     False      False        False